const QUESTIONS = [
  // === BATCH 1 (1-15) ===
  { id: 1, cat: "preferences", text: "Preferes um domingo preguiçoso em casa ou um domingo de aventura?", type: "thisorthat", options: ["Domingo preguiçoso em casa", "Domingo de aventura"] },
  { id: 2, cat: "us", text: "Qual foi o momento em que percebeste que estavas apaixonado/a por mim?", type: "text", options: [] },
  { id: 3, cat: "food", text: "Se só pudesses comer um prato português para o resto da vida, qual seria?", type: "choice", options: ["Francesinha", "Bacalhau à Brás", "Arroz de marisco", "Bitoque"] },
  { id: 4, cat: "entertainment", text: "Preferes ver um filme de terror juntos ou uma comédia romântica?", type: "thisorthat", options: ["Filme de terror", "Comédia romântica"] },
  { id: 5, cat: "dreams", text: "Onde imaginas que vamos estar daqui a 5 anos?", type: "text", options: [] },
  { id: 6, cat: "personality", text: "Qual destas palavras te descreve melhor em momentos de stress?", type: "choice", options: ["Explosivo/a", "Silencioso/a", "Racional", "Ansioso/a"] },
  { id: 7, cat: "spicy", text: "Já sentiste ciúmes de alguém na minha vida sem me dizeres?", type: "thisorthat", options: ["Sim, já senti", "Não, nunca"] },
  { id: 8, cat: "memories", text: "Qual é a memória mais engraçada que tens de nós dois?", type: "text", options: [] },
  { id: 9, cat: "travel", text: "Se pudéssemos fazer uma viagem amanhã, para onde ias?", type: "choice", options: ["Japão", "Maldivas", "Nova Iorque", "Islândia"] },
  { id: 10, cat: "intimacy", text: "O que te faz sentir mais amado/a?", type: "choice", options: ["Palavras de carinho", "Toque físico", "Gestos e surpresas", "Tempo de qualidade"] },
  { id: 11, cat: "whatif", text: "Se ganhássemos o Euromilhões, qual seria a primeira coisa que fazias?", type: "text", options: [] },
  { id: 12, cat: "preferences", text: "Preferes acordar cedo e aproveitar a manhã ou dormir até tarde?", type: "thisorthat", options: ["Acordar cedo", "Dormir até tarde"] },
  { id: 13, cat: "us", text: "Qual é a coisa que mais admiras em mim?", type: "text", options: [] },
  { id: 14, cat: "food", text: "Preferes cozinhar juntos ou que eu cozinhe para ti?", type: "thisorthat", options: ["Cozinhar juntos", "Que cozinhes para mim"] },
  { id: 15, cat: "spicy", text: "Qual é a coisa que nunca me contaste mas gostavas de contar?", type: "text", options: [] },

  // === BATCH 2 (16-30) ===
  { id: 16, cat: "entertainment", text: "Qual série poderias ver infinitas vezes sem cansar?", type: "text", options: [] },
  { id: 17, cat: "intimacy", text: "Preferes beijos longos e lentos ou beijos intensos e apaixonados?", type: "thisorthat", options: ["Longos e lentos", "Intensos e apaixonados"] },
  { id: 18, cat: "personality", text: "Em discussões, o que fazes primeiro?", type: "choice", options: ["Defendo o meu ponto até ao fim", "Fico calado/a a processar", "Tento ver o lado do outro", "Choro ou fico emocional"] },
  { id: 19, cat: "dreams", text: "Se pudesses ter qualquer profissão sem pensar em dinheiro, qual escolhias?", type: "text", options: [] },
  { id: 20, cat: "us", text: "Qual foi o nosso melhor date até hoje?", type: "text", options: [] },
  { id: 21, cat: "travel", text: "Preferes férias de praia ou férias de cidade e cultura?", type: "thisorthat", options: ["Férias de praia", "Férias de cidade e cultura"] },
  { id: 22, cat: "spicy", text: "Há alguma coisa que eu faço que te irrita mas nunca me disseste?", type: "text", options: [] },
  { id: 23, cat: "food", text: "Qual é o teu guilty pleasure alimentar que tens vergonha de admitir?", type: "text", options: [] },
  { id: 24, cat: "memories", text: "Qual foi o momento mais embaraçoso que passámos juntos?", type: "text", options: [] },
  { id: 25, cat: "preferences", text: "Preferes receber uma carta escrita à mão ou uma surpresa inesperada?", type: "thisorthat", options: ["Carta escrita à mão", "Surpresa inesperada"] },
  { id: 26, cat: "whatif", text: "Se pudesses reviver um dia da tua vida, qual escolhias?", type: "text", options: [] },
  { id: 27, cat: "intimacy", text: "Qual é a parte do meu corpo que mais gostas?", type: "choice", options: ["Os olhos", "O sorriso", "As mãos", "Outra coisa que não vou dizer aqui"] },
  { id: 28, cat: "personality", text: "Consideras-te mais racional ou emocional?", type: "thisorthat", options: ["Mais racional", "Mais emocional"] },
  { id: 29, cat: "entertainment", text: "Qual destes géneros musicais te define mais?", type: "choice", options: ["Pop/Mainstream", "Rock/Alternativo", "Hip-hop/R&B", "Eletrónica"] },
  { id: 30, cat: "spicy", text: "Se o teu ex te mandasse mensagem a dizer que cometeu um erro, o que fazias?", type: "choice", options: ["Ignorava completamente", "Respondia por educação", "Contava-te logo", "Depende do que dissesse"] },

  // === BATCH 3 (31-45) ===
  { id: 31, cat: "us", text: "Se pudesses mudar uma coisa na nossa relação, o que seria?", type: "text", options: [] },
  { id: 32, cat: "preferences", text: "Preferes estar rodeado/a de pessoas ou ter momentos a sós?", type: "thisorthat", options: ["Rodeado/a de pessoas", "Momentos a sós"] },
  { id: 33, cat: "dreams", text: "Que tipo de casa imaginas para nós no futuro?", type: "choice", options: ["Apartamento moderno na cidade", "Casa com jardim nos subúrbios", "Quinta no campo", "Casa perto do mar"] },
  { id: 34, cat: "food", text: "Preferes um jantar romântico em casa ou num restaurante fancy?", type: "thisorthat", options: ["Jantar romântico em casa", "Restaurante fancy"] },
  { id: 35, cat: "memories", text: "Qual foi a primeira coisa que reparaste em mim?", type: "text", options: [] },
  { id: 36, cat: "personality", text: "Qual é o teu maior medo irracional?", type: "text", options: [] },
  { id: 37, cat: "spicy", text: "Já pensaste em alguém de forma inapropriada enquanto estavas comigo?", type: "thisorthat", options: ["Sim, somos humanos", "Não, nunca"] },
  { id: 38, cat: "travel", text: "Se pudéssemos viver 6 meses num país estrangeiro, qual escolhias?", type: "text", options: [] },
  { id: 39, cat: "intimacy", text: "O que é mais importante para ti numa relação?", type: "choice", options: ["Confiança absoluta", "Paixão constante", "Comunicação aberta", "Independência mútua"] },
  { id: 40, cat: "whatif", text: "Se ficasses invisível por um dia, o que fazias?", type: "text", options: [] },
  { id: 41, cat: "entertainment", text: "Preferes ir ao cinema ou ver filmes em casa debaixo do cobertor?", type: "thisorthat", options: ["Cinema", "Em casa debaixo do cobertor"] },
  { id: 42, cat: "us", text: "Qual é a nossa maior força como casal?", type: "choice", options: ["A comunicação", "O humor", "A confiança", "A paixão"] },
  { id: 43, cat: "preferences", text: "Qual é a tua estação do ano preferida para viver momentos românticos?", type: "choice", options: ["Primavera", "Verão", "Outono", "Inverno"] },
  { id: 44, cat: "dreams", text: "Quantos filhos imaginas ter, se algum?", type: "choice", options: ["Nenhum", "Um", "Dois", "Três ou mais"] },
  { id: 45, cat: "spicy", text: "Qual é a mentira mais inocente que já me contaste?", type: "text", options: [] },

  // === BATCH 4 (46-60) ===
  { id: 46, cat: "intimacy", text: "Preferes carinho em público ou guardar a intimidade para quando estamos sozinhos?", type: "thisorthat", options: ["Carinho em público", "Intimidade a sós"] },
  { id: 47, cat: "food", text: "Qual é a comida que detestas mas que toda a gente adora?", type: "text", options: [] },
  { id: 48, cat: "personality", text: "Qual é o teu love language principal?", type: "choice", options: ["Palavras de afirmação", "Toque físico", "Atos de serviço", "Presentes"] },
  { id: 49, cat: "memories", text: "Qual foi o momento em que tiveste mais orgulho de mim?", type: "text", options: [] },
  { id: 50, cat: "travel", text: "Preferes aventura radical ou turismo relaxado?", type: "thisorthat", options: ["Aventura radical", "Turismo relaxado"] },
  { id: 51, cat: "us", text: "Qual é a música que te faz pensar em nós?", type: "text", options: [] },
  { id: 52, cat: "whatif", text: "Se pudesses ter um superpoder, qual escolhias?", type: "choice", options: ["Ler mentes", "Teletransporte", "Parar o tempo", "Voar"] },
  { id: 53, cat: "spicy", text: "Qual é o maior deal-breaker que tens numa relação?", type: "text", options: [] },
  { id: 54, cat: "preferences", text: "Preferes uma noite de jogo de tabuleiro ou uma noite de dança?", type: "thisorthat", options: ["Noite de jogo de tabuleiro", "Noite de dança"] },
  { id: 55, cat: "dreams", text: "Se pudesses aprender qualquer habilidade em 24 horas, qual seria?", type: "text", options: [] },
  { id: 56, cat: "entertainment", text: "Qual foi o último filme que te fez chorar?", type: "text", options: [] },
  { id: 57, cat: "personality", text: "Preferes liderar ou seguir?", type: "thisorthat", options: ["Liderar", "Seguir"] },
  { id: 58, cat: "intimacy", text: "Qual é o gesto romântico mais simples que te derrete?", type: "text", options: [] },
  { id: 59, cat: "food", text: "Se pudesses jantar com qualquer pessoa do mundo, quem escolhias?", type: "choice", options: ["Um chef famoso", "Uma celebridade", "Um familiar que já partiu", "Um líder histórico"] },
  { id: 60, cat: "spicy", text: "Já stalkeaste as redes sociais de alguém por ciúmes?", type: "thisorthat", options: ["Sim, quem nunca", "Não, respeito a privacidade"] },

  // === BATCH 5 (61-75) ===
  { id: 61, cat: "us", text: "Qual é o nosso inside joke favorito?", type: "text", options: [] },
  { id: 62, cat: "preferences", text: "Preferes café ou chá de manhã?", type: "thisorthat", options: ["Café, sempre", "Chá, obrigado/a"] },
  { id: 63, cat: "whatif", text: "Se tivesses que viver sem telemóvel ou sem computador, o que escolhias?", type: "thisorthat", options: ["Viver sem telemóvel", "Viver sem computador"] },
  { id: 64, cat: "memories", text: "Qual foi o presente mais significativo que já te dei?", type: "text", options: [] },
  { id: 65, cat: "travel", text: "Que destino tens na tua bucket list que nunca me contaste?", type: "text", options: [] },
  { id: 66, cat: "personality", text: "Qual destes valores é mais importante para ti?", type: "choice", options: ["Honestidade", "Lealdade", "Liberdade", "Ambição"] },
  { id: 67, cat: "spicy", text: "Qual é a tua opinião mais controversa que guardas para ti?", type: "text", options: [] },
  { id: 68, cat: "intimacy", text: "O que te atrai mais: confiança ou mistério?", type: "thisorthat", options: ["Confiança", "Mistério"] },
  { id: 69, cat: "food", text: "Qual é o snack que comes escondido/a sem partilhar?", type: "text", options: [] },
  { id: 70, cat: "entertainment", text: "Se a nossa vida fosse um filme, que género seria?", type: "choice", options: ["Comédia romântica", "Drama intenso", "Aventura épica", "Indie artístico"] },
  { id: 71, cat: "dreams", text: "Preferes segurança financeira ou fazer o que amas mesmo ganhando menos?", type: "thisorthat", options: ["Segurança financeira", "Fazer o que amo"] },
  { id: 72, cat: "us", text: "Qual é a coisa mais parva que já discutimos?", type: "text", options: [] },
  { id: 73, cat: "personality", text: "Achas que sou mais parecido/a com o meu pai ou com a minha mãe?", type: "thisorthat", options: ["Com o teu pai", "Com a tua mãe"] },
  { id: 74, cat: "whatif", text: "Se pudesses trocar de vida com alguém por uma semana, quem escolhias?", type: "text", options: [] },
  { id: 75, cat: "spicy", text: "Há alguma fantasia que tens vergonha de me contar?", type: "thisorthat", options: ["Sim, talvez um dia", "Não, já sabes tudo"] },

  // === BATCH 6 (76-90) ===
  { id: 76, cat: "memories", text: "Qual foi o nosso pior momento como casal e o que aprendemos com ele?", type: "text", options: [] },
  { id: 77, cat: "preferences", text: "Preferes uma casa arrumada ao milímetro ou um caos criativo?", type: "thisorthat", options: ["Arrumada ao milímetro", "Caos criativo"] },
  { id: 78, cat: "food", text: "Qual é o restaurante onde gostavas de me levar um dia?", type: "text", options: [] },
  { id: 79, cat: "travel", text: "Preferes viajar de carro numa road trip ou de avião para longe?", type: "thisorthat", options: ["Road trip de carro", "Avião para longe"] },
  { id: 80, cat: "entertainment", text: "Que banda ou artista gostavas de ver ao vivo comigo?", type: "text", options: [] },
  { id: 81, cat: "intimacy", text: "O que mais gostas de fazer quando estamos juntos em casa?", type: "choice", options: ["Abraçar no sofá", "Cozinhar juntos", "Conversar durante horas", "Outros planos mais íntimos"] },
  { id: 82, cat: "personality", text: "Como lidas com a saudade à distância?", type: "choice", options: ["Mantenho-me ocupado/a", "Falo contigo o máximo possível", "Escrevo o que sinto", "Sofro em silêncio"] },
  { id: 83, cat: "spicy", text: "Se descobrisses que eu segui um/a ex no Instagram, como reagias?", type: "choice", options: ["Não me importava nada", "Ficava incomodado/a mas não dizia", "Perguntava diretamente porquê", "Ficava furioso/a"] },
  { id: 84, cat: "us", text: "O que é que eu faço que te faz rir sempre?", type: "text", options: [] },
  { id: 85, cat: "dreams", text: "Se pudéssemos ter um negócio juntos, o que seria?", type: "text", options: [] },
  { id: 86, cat: "whatif", text: "Se tivesses 24 horas para viver sem consequências, o que fazias?", type: "text", options: [] },
  { id: 87, cat: "preferences", text: "Preferes ser surpreendido/a ou planear tudo ao detalhe?", type: "thisorthat", options: ["Ser surpreendido/a", "Planear tudo"] },
  { id: 88, cat: "food", text: "Preferes pequeno-almoço na cama ou brunch fora de casa?", type: "thisorthat", options: ["Pequeno-almoço na cama", "Brunch fora de casa"] },
  { id: 89, cat: "intimacy", text: "Qual é a coisa mais romântica que já fiz por ti?", type: "text", options: [] },
  { id: 90, cat: "spicy", text: "Já comparaste a nossa relação com a de outros casais?", type: "thisorthat", options: ["Sim, é inevitável", "Não, cada relação é única"] },

  // === BATCH 7 (91-105) ===
  { id: 91, cat: "entertainment", text: "Preferes um concerto intimista ou um festival enorme?", type: "thisorthat", options: ["Concerto intimista", "Festival enorme"] },
  { id: 92, cat: "us", text: "O que é que mais te custa na distância entre nós?", type: "text", options: [] },
  { id: 93, cat: "personality", text: "Consideras-te mais otimista ou realista?", type: "thisorthat", options: ["Otimista", "Realista"] },
  { id: 94, cat: "travel", text: "Qual foi a melhor viagem que já fizemos juntos?", type: "text", options: [] },
  { id: 95, cat: "dreams", text: "Se o dinheiro não fosse problema, como seria o nosso casamento ideal?", type: "text", options: [] },
  { id: 96, cat: "food", text: "Qual é a comida de conforto que comes quando estás triste?", type: "text", options: [] },
  { id: 97, cat: "spicy", text: "Qual é a coisa que mais te assusta sobre o nosso futuro?", type: "text", options: [] },
  { id: 98, cat: "memories", text: "Lembras-te da primeira mensagem que trocámos? O que sentiste?", type: "text", options: [] },
  { id: 99, cat: "whatif", text: "Se pudesses ler a minha mente por 5 minutos, fá-lo-ias?", type: "thisorthat", options: ["Sim, sem hesitar", "Não, há coisas que é melhor não saber"] },
  { id: 100, cat: "preferences", text: "Preferes noites de verão ou tardes de inverno junto à lareira?", type: "thisorthat", options: ["Noites de verão", "Tardes de inverno junto à lareira"] },
  { id: 101, cat: "intimacy", text: "Qual é a tua linguagem de amor quando queres mostrar carinho?", type: "choice", options: ["Dizer coisas bonitas", "Abraços e beijos", "Fazer favores e surpresas", "Dar presentes pensados"] },
  { id: 102, cat: "personality", text: "O que te irrita mais nas outras pessoas?", type: "choice", options: ["Falsidade", "Arrogância", "Falta de consideração", "Vitimização"] },
  { id: 103, cat: "us", text: "Se pudesses descrever a nossa relação em 3 palavras, quais seriam?", type: "text", options: [] },
  { id: 104, cat: "dreams", text: "Preferes ter muito dinheiro e pouco tempo livre ou pouco dinheiro e muito tempo livre?", type: "thisorthat", options: ["Muito dinheiro, pouco tempo", "Pouco dinheiro, muito tempo"] },
  { id: 105, cat: "spicy", text: "Já tiveste vontade de ir embora no meio de uma discussão nossa?", type: "thisorthat", options: ["Sim, já pensei nisso", "Não, enfrento sempre"] },

  // === BATCH 8 (106-120) ===
  { id: 106, cat: "food", text: "Se tivéssemos um restaurante, que tipo de comida servíamos?", type: "choice", options: ["Comida portuguesa tradicional", "Sushi e comida asiática", "Comida italiana", "Comida de fusão criativa"] },
  { id: 107, cat: "travel", text: "Preferes umas férias com plano detalhado ou totalmente improvisadas?", type: "thisorthat", options: ["Plano detalhado", "Totalmente improvisadas"] },
  { id: 108, cat: "whatif", text: "Se pudesses viver numa época diferente, qual escolhias?", type: "choice", options: ["Anos 20 (jazz e glamour)", "Anos 60 (paz e amor)", "Anos 80 (música e néon)", "O futuro daqui a 100 anos"] },
  { id: 109, cat: "entertainment", text: "Qual é a música que nos define como casal?", type: "text", options: [] },
  { id: 110, cat: "intimacy", text: "O que te faz sentir mais desejado/a?", type: "text", options: [] },
  { id: 111, cat: "preferences", text: "Preferes dar presentes ou receber presentes?", type: "thisorthat", options: ["Dar presentes", "Receber presentes"] },
  { id: 112, cat: "spicy", text: "Achas que a monogamia é natural ou uma construção social?", type: "thisorthat", options: ["É natural", "É uma construção social"] },
  { id: 113, cat: "memories", text: "Qual é o cheiro que te faz lembrar de mim?", type: "text", options: [] },
  { id: 114, cat: "personality", text: "Quando tens um problema, preferes resolvê-lo sozinho/a ou pedir ajuda?", type: "thisorthat", options: ["Resolver sozinho/a", "Pedir ajuda"] },
  { id: 115, cat: "dreams", text: "Que tradição gostavas de criar para a nossa família no futuro?", type: "text", options: [] },
  { id: 116, cat: "us", text: "Se tivéssemos um animal de estimação juntos, qual seria?", type: "choice", options: ["Cão", "Gato", "Algo exótico", "Um de cada"] },
  { id: 117, cat: "food", text: "Preferes comida caseira ou comida de rua?", type: "thisorthat", options: ["Comida caseira", "Comida de rua"] },
  { id: 118, cat: "travel", text: "Qual é o sítio em Portugal que gostavas de explorar comigo?", type: "text", options: [] },
  { id: 119, cat: "whatif", text: "Se encontrasses uma máquina do tempo, ias ao passado ou ao futuro?", type: "thisorthat", options: ["Ao passado", "Ao futuro"] },
  { id: 120, cat: "spicy", text: "O que pensaste de mim quando me conheceste que nunca me disseste?", type: "text", options: [] },

  // === BATCH 9 (121-135) ===
  { id: 121, cat: "intimacy", text: "Preferes manhãs lentas com mimos ou noites intensas?", type: "thisorthat", options: ["Manhãs lentas com mimos", "Noites intensas"] },
  { id: 122, cat: "entertainment", text: "Se pudéssemos ir a qualquer evento no mundo, qual escolhias?", type: "choice", options: ["Super Bowl", "Festival de Cannes", "Carnaval do Rio", "Réveillon em Sydney"] },
  { id: 123, cat: "personality", text: "Qual é a qualidade que mais valorizas num amigo?", type: "choice", options: ["Lealdade", "Honestidade", "Sentido de humor", "Disponibilidade"] },
  { id: 124, cat: "us", text: "Qual é o hábito meu que achas mais fofo?", type: "text", options: [] },
  { id: 125, cat: "preferences", text: "Preferes viver perto da família ou noutro país juntos?", type: "thisorthat", options: ["Perto da família", "Noutro país juntos"] },
  { id: 126, cat: "dreams", text: "Se pudéssemos comprar casa amanhã, como seria o teu espaço ideal?", type: "text", options: [] },
  { id: 127, cat: "food", text: "Qual é a sobremesa que não consegues resistir?", type: "choice", options: ["Pastel de nata", "Bolo de chocolate", "Gelado", "Cheesecake"] },
  { id: 128, cat: "spicy", text: "Já mentiste sobre gostar de algo que eu fiz só para não me magoar?", type: "thisorthat", options: ["Sim, claro que já", "Não, sou sempre honesto/a"] },
  { id: 129, cat: "memories", text: "Qual foi o dia mais difícil que passámos juntos e como o superámos?", type: "text", options: [] },
  { id: 130, cat: "travel", text: "Se pudéssemos viver numa van durante um mês, onde íamos?", type: "text", options: [] },
  { id: 131, cat: "whatif", text: "Se descobrisses que temos personalidades completamente opostas num teste, preocupavas-te?", type: "thisorthat", options: ["Sim, ficava a pensar nisso", "Não, os opostos atraem-se"] },
  { id: 132, cat: "personality", text: "Consideras-te ciumento/a?", type: "choice", options: ["Nada ciumento/a", "Um pouco, saudável", "Bastante, mas controlo", "Muito, e nem sempre controlo"] },
  { id: 133, cat: "intimacy", text: "Qual é a tua zona mais sensível ao toque?", type: "text", options: [] },
  { id: 134, cat: "entertainment", text: "Preferes um podcast juntos ou música de fundo?", type: "thisorthat", options: ["Podcast juntos", "Música de fundo"] },
  { id: 135, cat: "spicy", text: "Achas que é possível ser amigo/a de um ex?", type: "thisorthat", options: ["Sim, é possível", "Não, é arriscado"] },

  // === BATCH 10 (136-150) ===
  { id: 136, cat: "us", text: "Se pudesses voltar ao início da nossa relação sabendo o que sabes agora, o que fazias diferente?", type: "text", options: [] },
  { id: 137, cat: "preferences", text: "Preferes um presente caro ou uma experiência memorável?", type: "thisorthat", options: ["Presente caro", "Experiência memorável"] },
  { id: 138, cat: "dreams", text: "Se pudéssemos criar uma tradição de casal, qual seria?", type: "text", options: [] },
  { id: 139, cat: "food", text: "Preferes um jantar de 5 pratos ou um bom petisco com cerveja?", type: "thisorthat", options: ["Jantar de 5 pratos", "Petisco com cerveja"] },
  { id: 140, cat: "personality", text: "Qual é a emoção que tens mais dificuldade em expressar?", type: "choice", options: ["Raiva", "Tristeza", "Vulnerabilidade", "Gratidão"] },
  { id: 141, cat: "travel", text: "Se pudéssemos fazer um cruzeiro, para onde ia?", type: "choice", options: ["Mediterrâneo", "Caraíbas", "Fiordes noruegueses", "Sudeste asiático"] },
  { id: 142, cat: "spicy", text: "Qual é a coisa mais egoísta que já fizeste numa relação?", type: "text", options: [] },
  { id: 143, cat: "memories", text: "Qual é a foto nossa favorita e porquê?", type: "text", options: [] },
  { id: 144, cat: "whatif", text: "Se tivesses que escolher entre fama e anonimato, o que escolhias?", type: "thisorthat", options: ["Fama", "Anonimato"] },
  { id: 145, cat: "entertainment", text: "Qual foi o livro ou filme que mais te mudou como pessoa?", type: "text", options: [] },
  { id: 146, cat: "intimacy", text: "Achas que a nossa vida íntima é satisfatória?", type: "choice", options: ["Sim, completamente", "Sim, mas podia melhorar", "Mais ou menos", "Precisamos de falar sobre isso"] },
  { id: 147, cat: "us", text: "Qual é o nosso ponto fraco como casal?", type: "text", options: [] },
  { id: 148, cat: "preferences", text: "Preferes rotina ou espontaneidade no dia-a-dia?", type: "thisorthat", options: ["Rotina", "Espontaneidade"] },
  { id: 149, cat: "personality", text: "Achas que as pessoas podem realmente mudar?", type: "thisorthat", options: ["Sim, com esforço", "Não, a essência mantém-se"] },
  { id: 150, cat: "spicy", text: "Se eu te pedisse para mostrar todas as tuas conversas, terias problema?", type: "thisorthat", options: ["Nenhum problema", "Preferia que não"] },

  // === BATCH 11 (151-165) ===
  { id: 151, cat: "dreams", text: "Se pudéssemos reformar-nos aos 40, o que fazíamos com o tempo?", type: "text", options: [] },
  { id: 152, cat: "food", text: "Qual é o prato que gostavas de aprender a cozinhar para mim?", type: "text", options: [] },
  { id: 153, cat: "travel", text: "Preferes um hotel de luxo ou um Airbnb com personalidade?", type: "thisorthat", options: ["Hotel de luxo", "Airbnb com personalidade"] },
  { id: 154, cat: "entertainment", text: "Se pudéssemos ter um hobby em conjunto, qual escolhias?", type: "choice", options: ["Dança a dois", "Cozinhar pratos novos", "Escalada ou desporto", "Aprender uma língua"] },
  { id: 155, cat: "personality", text: "Qual é o hábito que tens e que gostavas de mudar?", type: "text", options: [] },
  { id: 156, cat: "us", text: "Em que aspeto é que crescemos mais como casal?", type: "text", options: [] },
  { id: 157, cat: "intimacy", text: "Preferes sexting ou chamadas de voz à noite?", type: "thisorthat", options: ["Sexting", "Chamadas de voz"] },
  { id: 158, cat: "spicy", text: "Qual foi a maior red flag que ignoraste em mim no início?", type: "text", options: [] },
  { id: 159, cat: "memories", text: "Qual foi a surpresa que te fiz que mais gostaste?", type: "text", options: [] },
  { id: 160, cat: "whatif", text: "Se eu tivesse que mudar de país por trabalho, o que fazias?", type: "choice", options: ["Ia contigo sem pensar", "Tentava arranjar algo lá também", "Mantínhamos à distância", "Depende do país e condições"] },
  { id: 161, cat: "preferences", text: "Preferes um aniversário tranquilo ou uma festa surpresa?", type: "thisorthat", options: ["Aniversário tranquilo", "Festa surpresa"] },
  { id: 162, cat: "food", text: "Se pudéssemos comer comida de um país para sempre, qual escolhias?", type: "choice", options: ["Italiana", "Japonesa", "Mexicana", "Portuguesa"] },
  { id: 163, cat: "personality", text: "Achas que és mais parecido/a com quem eras há 5 anos ou completamente diferente?", type: "thisorthat", options: ["Bastante parecido/a", "Completamente diferente"] },
  { id: 164, cat: "dreams", text: "Qual é o sonho que tens para nós que nunca me contaste?", type: "text", options: [] },
  { id: 165, cat: "spicy", text: "Se um/a amigo/a meu/minha te fizesse uma confidência sobre mim, contavas-me?", type: "choice", options: ["Sim, sempre", "Depende do que fosse", "Não, respeitava a confiança", "Confrontava-te sem revelar a fonte"] },

  // === BATCH 12 (166-180) ===
  { id: 166, cat: "travel", text: "Qual foi o momento mais mágico numa viagem que fizemos?", type: "text", options: [] },
  { id: 167, cat: "intimacy", text: "O que posso fazer para te fazer sentir mais especial?", type: "text", options: [] },
  { id: 168, cat: "us", text: "Preferes resolver problemas na hora ou dar tempo para pensar?", type: "thisorthat", options: ["Resolver na hora", "Dar tempo para pensar"] },
  { id: 169, cat: "entertainment", text: "Se pudéssemos estar num reality show, qual escolhias?", type: "choice", options: ["The Amazing Race", "MasterChef a Dois", "Love Island", "Nenhum, prefiro privacidade"] },
  { id: 170, cat: "memories", text: "Qual é a gargalhada nossa que nunca te vais esquecer?", type: "text", options: [] },
  { id: 171, cat: "preferences", text: "Preferes dormir com a janela aberta ou fechada?", type: "thisorthat", options: ["Janela aberta", "Janela fechada"] },
  { id: 172, cat: "spicy", text: "Já pesquisaste alguma coisa sobre mim que eu não saiba?", type: "thisorthat", options: ["Sim, admito", "Não, respeito o espaço"] },
  { id: 173, cat: "food", text: "Qual é a bebida que pedes quando queres impressionar?", type: "choice", options: ["Vinho tinto", "Cocktail clássico", "Champanhe", "Cerveja artesanal"] },
  { id: 174, cat: "whatif", text: "Se pudéssemos viver sem trabalhar, como seria o nosso dia típico?", type: "text", options: [] },
  { id: 175, cat: "personality", text: "Qual destes medos é mais real para ti?", type: "choice", options: ["Ficar sozinho/a", "Não ser suficiente", "Falhar na vida", "Perder quem amo"] },
  { id: 176, cat: "dreams", text: "Se pudéssemos criar algo juntos que mudasse o mundo, o que seria?", type: "text", options: [] },
  { id: 177, cat: "intimacy", text: "Preferes dormir de conchinha ou cada um no seu lado?", type: "thisorthat", options: ["De conchinha, sempre", "Cada um no seu lado"] },
  { id: 178, cat: "us", text: "Qual é a coisa mais simples que faço e que te deixa feliz?", type: "text", options: [] },
  { id: 179, cat: "travel", text: "Preferes explorar capitais europeias ou ilhas paradisíacas?", type: "thisorthat", options: ["Capitais europeias", "Ilhas paradisíacas"] },
  { id: 180, cat: "spicy", text: "Qual é a insegurança que tens na nossa relação e nunca admitiste?", type: "text", options: [] },

  // === BATCH 13 (181-195) ===
  { id: 181, cat: "food", text: "Preferes cozinhar uma receita nova ou aperfeiçoar uma que já sabes?", type: "thisorthat", options: ["Receita nova", "Aperfeiçoar uma que já sei"] },
  { id: 182, cat: "entertainment", text: "Qual é a série que te acompanhou numa fase difícil da vida?", type: "text", options: [] },
  { id: 183, cat: "personality", text: "Consideras-te mais introvertido/a ou extrovertido/a?", type: "thisorthat", options: ["Introvertido/a", "Extrovertido/a"] },
  { id: 184, cat: "memories", text: "Qual foi o momento em que sentiste que esta relação era para a vida?", type: "text", options: [] },
  { id: 185, cat: "us", text: "Se tivéssemos que escolher uma atividade para fazer toda a semana juntos, qual seria?", type: "choice", options: ["Treinar juntos", "Cozinhar juntos", "Ver séries juntos", "Passear juntos"] },
  { id: 186, cat: "preferences", text: "Preferes uma casa cheia de plantas ou uma casa minimalista?", type: "thisorthat", options: ["Cheia de plantas", "Minimalista"] },
  { id: 187, cat: "spicy", text: "Já pensaste que podíamos não resultar como casal?", type: "thisorthat", options: ["Sim, nos momentos difíceis", "Não, sempre acreditei em nós"] },
  { id: 188, cat: "dreams", text: "Se tivéssemos filhos, como gostavas de os educar?", type: "text", options: [] },
  { id: 189, cat: "intimacy", text: "O que é que te põe de bom humor instantaneamente?", type: "choice", options: ["Um beijo teu", "Uma mensagem fofa", "Música que gosto", "Comida boa"] },
  { id: 190, cat: "travel", text: "Se pudéssemos fazer voluntariado juntos algures no mundo, onde seria?", type: "text", options: [] },
  { id: 191, cat: "whatif", text: "Se eu perdesse a memória, como me reconquistavas?", type: "text", options: [] },
  { id: 192, cat: "food", text: "Qual é o restaurante em que tivemos a melhor refeição juntos?", type: "text", options: [] },
  { id: 193, cat: "personality", text: "Qual destas situações te causa mais ansiedade?", type: "choice", options: ["Falar em público", "Conflitos com pessoas próximas", "Incerteza sobre o futuro", "Estar num sítio novo sozinho/a"] },
  { id: 194, cat: "entertainment", text: "Preferes um documentário interessante ou um thriller emocionante?", type: "thisorthat", options: ["Documentário", "Thriller"] },
  { id: 195, cat: "spicy", text: "Se um/a amigo/a teu/tua me desse em cima, o que esperavas que eu fizesse?", type: "choice", options: ["Rejeitar e contar-te logo", "Rejeitar e nunca contar", "Afastar-se dessa pessoa", "Depende da situação"] },

  // === BATCH 14 (196-210) ===
  { id: 196, cat: "us", text: "Qual é o nosso ritual de casal favorito?", type: "text", options: [] },
  { id: 197, cat: "preferences", text: "Preferes planear as férias com meses de antecedência ou decidir na última hora?", type: "thisorthat", options: ["Meses de antecedência", "Última hora"] },
  { id: 198, cat: "dreams", text: "Se pudéssemos ter um ano sabático juntos, como o passavas?", type: "text", options: [] },
  { id: 199, cat: "intimacy", text: "Qual é a mensagem minha que guardas com mais carinho?", type: "text", options: [] },
  { id: 200, cat: "food", text: "Preferes um brunch saudável ou um brunch com panquecas e bacon?", type: "thisorthat", options: ["Brunch saudável", "Panquecas e bacon"] },
  { id: 201, cat: "travel", text: "Qual é o país que te assusta um pouco mas gostavas de visitar?", type: "text", options: [] },
  { id: 202, cat: "personality", text: "Achas que sou bom/boa a ouvir-te quando precisas de desabafar?", type: "choice", options: ["Sim, és ótimo/a", "Às vezes, depende", "Podias melhorar", "Precisamos de trabalhar nisso"] },
  { id: 203, cat: "spicy", text: "Qual é a tua opinião honesta sobre a minha família?", type: "text", options: [] },
  { id: 204, cat: "entertainment", text: "Se pudéssemos aprender uma dança juntos, qual seria?", type: "choice", options: ["Salsa", "Bachata", "Valsa", "Kizomba"] },
  { id: 205, cat: "memories", text: "Qual é o momento em que mais te irritei e como me perdoaste?", type: "text", options: [] },
  { id: 206, cat: "whatif", text: "Se pudéssemos adotar qualquer animal exótico, qual escolhias?", type: "choice", options: ["Panda vermelho", "Raposa", "Lontra", "Coruja"] },
  { id: 207, cat: "preferences", text: "Preferes acordar com um beijo ou com o cheiro a café?", type: "thisorthat", options: ["Com um beijo", "Com cheiro a café"] },
  { id: 208, cat: "us", text: "O que aprendeste sobre ti mesmo/a desde que estás comigo?", type: "text", options: [] },
  { id: 209, cat: "intimacy", text: "Preferes mais romance no dia-a-dia ou gestos grandes em datas especiais?", type: "thisorthat", options: ["Romance no dia-a-dia", "Gestos grandes em datas especiais"] },
  { id: 210, cat: "spicy", text: "Há algo que fazemos como casal que achas que não é normal?", type: "text", options: [] },

  // === BATCH 15 (211-225) ===
  { id: 211, cat: "personality", text: "Qual é a tua forma de pedir desculpa?", type: "choice", options: ["Digo desculpa diretamente", "Faço algo especial sem dizer nada", "Preciso de tempo antes de pedir desculpa", "Evito o assunto e espero que passe"] },
  { id: 212, cat: "food", text: "Se só pudéssemos comer uma fruta para sempre, qual era?", type: "choice", options: ["Morangos", "Manga", "Uvas", "Pêssego"] },
  { id: 213, cat: "travel", text: "Preferes uma aventura na selva ou uma experiência no deserto?", type: "thisorthat", options: ["Aventura na selva", "Experiência no deserto"] },
  { id: 214, cat: "dreams", text: "Onde te vês profissionalmente daqui a 10 anos?", type: "text", options: [] },
  { id: 215, cat: "entertainment", text: "Qual é o teu guilty pleasure em termos de entretenimento?", type: "text", options: [] },
  { id: 216, cat: "us", text: "Achas que comunicamos bem os nossos sentimentos?", type: "choice", options: ["Sim, muito bem", "Na maioria das vezes", "Podemos melhorar bastante", "Temos dificuldade nisso"] },
  { id: 217, cat: "spicy", text: "Se eu engordasse 20 quilos, isso afetaria a tua atração por mim?", type: "thisorthat", options: ["Não, amo-te igual", "Seria honesto/a, sim afetaria um pouco"] },
  { id: 218, cat: "memories", text: "Qual foi o nosso Natal ou Ano Novo mais especial?", type: "text", options: [] },
  { id: 219, cat: "whatif", text: "Se pudéssemos ter um chef pessoal ou um motorista pessoal, o que escolhias?", type: "thisorthat", options: ["Chef pessoal", "Motorista pessoal"] },
  { id: 220, cat: "intimacy", text: "O que é que eu digo que te faz sentir mais seguro/a na relação?", type: "text", options: [] },
  { id: 221, cat: "preferences", text: "Preferes uma manhã produtiva ou uma manhã tranquila?", type: "thisorthat", options: ["Manhã produtiva", "Manhã tranquila"] },
  { id: 222, cat: "personality", text: "Qual é a tua maior vulnerabilidade emocional?", type: "text", options: [] },
  { id: 223, cat: "food", text: "Preferes comida picante ou sabores suaves?", type: "thisorthat", options: ["Comida picante", "Sabores suaves"] },
  { id: 224, cat: "travel", text: "Que cidade europeia gostavas de visitar numa escapadinha de fim de semana?", type: "choice", options: ["Paris", "Amesterdão", "Barcelona", "Praga"] },
  { id: 225, cat: "spicy", text: "Qual é a coisa que mudavas no meu corpo se pudesses?", type: "text", options: [] },

  // === BATCH 16 (226-240) ===
  { id: 226, cat: "us", text: "Qual foi a maior prova de amor que me deste?", type: "text", options: [] },
  { id: 227, cat: "dreams", text: "Se pudéssemos construir a casa dos nossos sonhos, que divisão seria a mais especial?", type: "choice", options: ["A cozinha aberta", "O quarto com vista", "O escritório partilhado", "O jardim/terraço"] },
  { id: 228, cat: "entertainment", text: "Preferes ver desporto juntos ou uma maratona de séries?", type: "thisorthat", options: ["Desporto juntos", "Maratona de séries"] },
  { id: 229, cat: "food", text: "Qual é o prato que a tua mãe faz melhor que ninguém?", type: "text", options: [] },
  { id: 230, cat: "personality", text: "Preferes ter razão ou ter paz?", type: "thisorthat", options: ["Ter razão", "Ter paz"] },
  { id: 231, cat: "intimacy", text: "Qual foi o nosso beijo mais memorável?", type: "text", options: [] },
  { id: 232, cat: "spicy", text: "Já ficaste atraído/a por alguém enquanto estávamos juntos?", type: "thisorthat", options: ["Sim, mas não atuei", "Não, nunca"] },
  { id: 233, cat: "memories", text: "Qual é o sítio que visitámos e que gostavas de voltar comigo?", type: "text", options: [] },
  { id: 234, cat: "travel", text: "Preferes acampar debaixo das estrelas ou glamping com conforto?", type: "thisorthat", options: ["Acampar debaixo das estrelas", "Glamping com conforto"] },
  { id: 235, cat: "whatif", text: "Se pudesses escolher um talento artístico, qual seria?", type: "choice", options: ["Cantar lindamente", "Pintar quadros", "Tocar guitarra", "Escrever livros"] },
  { id: 236, cat: "preferences", text: "Preferes um dia de chuva em casa ou um dia de sol na praia?", type: "thisorthat", options: ["Dia de chuva em casa", "Dia de sol na praia"] },
  { id: 237, cat: "us", text: "Se pudéssemos ter uma date night perfeita, como seria?", type: "text", options: [] },
  { id: 238, cat: "personality", text: "Qual é a lição de vida mais importante que aprendeste?", type: "text", options: [] },
  { id: 239, cat: "food", text: "Se pudéssemos abrir um café juntos, qual seria o conceito?", type: "choice", options: ["Café literário acolhedor", "Brunch spot moderno", "Café com jogos de tabuleiro", "Pastelaria artesanal"] },
  { id: 240, cat: "spicy", text: "Achas que sou mais bonito/a ou mais sexy?", type: "thisorthat", options: ["Mais bonito/a", "Mais sexy"] },

  // === BATCH 17 (241-255) ===
  { id: 241, cat: "intimacy", text: "O que te faz sentir mais conectado/a comigo emocionalmente?", type: "text", options: [] },
  { id: 242, cat: "dreams", text: "Se pudéssemos mudar-nos para qualquer cidade do mundo amanhã, para onde íamos?", type: "text", options: [] },
  { id: 243, cat: "entertainment", text: "Qual é o teu álbum de música favorito de sempre?", type: "text", options: [] },
  { id: 244, cat: "travel", text: "Preferes uma viagem solo ou sempre a dois?", type: "thisorthat", options: ["Às vezes solo é bom", "Sempre a dois"] },
  { id: 245, cat: "preferences", text: "Preferes acordar com alarme ou naturalmente?", type: "thisorthat", options: ["Com alarme", "Naturalmente"] },
  { id: 246, cat: "us", text: "Qual é o compromisso mais difícil que já fizemos na relação?", type: "text", options: [] },
  { id: 247, cat: "spicy", text: "Se descobrisses que eu tinha um segredo grande, preferias saber ou não?", type: "thisorthat", options: ["Quero saber sempre", "Depende do segredo"] },
  { id: 248, cat: "food", text: "Qual é o pior prato que já tentaste fazer?", type: "text", options: [] },
  { id: 249, cat: "personality", text: "Quando tens medo, como reages?", type: "choice", options: ["Enfrento de frente", "Congelo e preciso de tempo", "Fujo da situação", "Procuro apoio em alguém"] },
  { id: 250, cat: "memories", text: "Qual foi a viagem mais inesquecível que fizemos?", type: "text", options: [] },
  { id: 251, cat: "whatif", text: "Se eu te propusesse casamento amanhã de forma completamente inesperada, como reagias?", type: "choice", options: ["Dizia sim sem hesitar", "Ficava em choque mas dizia sim", "Pedia para falarmos sobre isso", "Acho que é cedo"] },
  { id: 252, cat: "intimacy", text: "Preferes ser o/a grande colher ou a pequena colher?", type: "thisorthat", options: ["Grande colher", "Pequena colher"] },
  { id: 253, cat: "personality", text: "Achas que és mais cabeça ou coração?", type: "thisorthat", options: ["Mais cabeça", "Mais coração"] },
  { id: 254, cat: "dreams", text: "Qual é o objetivo de vida que nunca me disseste?", type: "text", options: [] },
  { id: 255, cat: "spicy", text: "Já fingiste gostar de algo na cama só para me agradar?", type: "thisorthat", options: ["Sim, já aconteceu", "Não, sou sempre genuíno/a"] },

  // === BATCH 18 (256-270) ===
  { id: 256, cat: "food", text: "Preferes um petit gâteau de chocolate ou uma tarte de limão?", type: "thisorthat", options: ["Petit gâteau de chocolate", "Tarte de limão"] },
  { id: 257, cat: "travel", text: "Se pudéssemos fazer uma road trip pela Europa, que países incluías?", type: "text", options: [] },
  { id: 258, cat: "entertainment", text: "Qual personagem de ficção achas que se parece mais comigo?", type: "text", options: [] },
  { id: 259, cat: "us", text: "Qual é o nosso maior desafio na distância?", type: "choice", options: ["Falta de contacto físico", "Diferença de horários", "Ciúmes e insegurança", "Não partilhar o dia-a-dia"] },
  { id: 260, cat: "personality", text: "Qual é a qualidade minha que mais te complementa?", type: "text", options: [] },
  { id: 261, cat: "preferences", text: "Preferes uma noite de jogos ou uma noite de conversa profunda?", type: "thisorthat", options: ["Noite de jogos", "Noite de conversa profunda"] },
  { id: 262, cat: "spicy", text: "Qual é a coisa mais arriscada que já fizeste por amor?", type: "text", options: [] },
  { id: 263, cat: "memories", text: "Qual foi a chamada ou videochamada nossa mais especial?", type: "text", options: [] },
  { id: 264, cat: "dreams", text: "Se pudéssemos ter qualquer tipo de casamento, como seria?", type: "choice", options: ["Na praia ao pôr do sol", "Numa quinta rústica", "Só nós dois num destino exótico", "Cerimónia grande com toda a família"] },
  { id: 265, cat: "intimacy", text: "Qual é a parte do dia em que mais sentes a minha falta?", type: "choice", options: ["De manhã ao acordar", "À hora de almoço", "Ao fim da tarde", "À noite antes de dormir"] },
  { id: 266, cat: "whatif", text: "Se pudéssemos comunicar telepaticamente, achas que seria bom ou mau?", type: "thisorthat", options: ["Seria incrível", "Seria desastroso"] },
  { id: 267, cat: "food", text: "Qual é o teu pedido de pizza ideal?", type: "text", options: [] },
  { id: 268, cat: "travel", text: "Preferes turismo de aventura ou turismo gastronómico?", type: "thisorthat", options: ["Turismo de aventura", "Turismo gastronómico"] },
  { id: 269, cat: "personality", text: "Achas que és uma pessoa difícil de conviver?", type: "choice", options: ["Não, sou fácil", "Às vezes posso ser", "Sim, tenho consciência disso", "Depende de quem perguntares"] },
  { id: 270, cat: "spicy", text: "Se o nosso melhor amigo/a me dissesse algo mau sobre ti, eu devia contar-te?", type: "thisorthat", options: ["Sim, quero saber tudo", "Não, resolve entre vocês"] },

  // === BATCH 19 (271-285) ===
  { id: 271, cat: "entertainment", text: "Preferes uma noite de karaoke ou uma noite de stand-up comedy?", type: "thisorthat", options: ["Noite de karaoke", "Stand-up comedy"] },
  { id: 272, cat: "us", text: "O que significa fidelidade para ti?", type: "text", options: [] },
  { id: 273, cat: "intimacy", text: "Qual é o elogio meu que mais te marcou?", type: "text", options: [] },
  { id: 274, cat: "dreams", text: "Se pudesses garantir uma coisa para o nosso futuro, o que seria?", type: "choice", options: ["Saúde para ambos", "Estabilidade financeira", "Estarmos sempre juntos", "Felicidade constante"] },
  { id: 275, cat: "food", text: "Qual é a comida que cheira mal mas sabe bem?", type: "text", options: [] },
  { id: 276, cat: "preferences", text: "Preferes tomar banho de manhã ou à noite?", type: "thisorthat", options: ["De manhã", "À noite"] },
  { id: 277, cat: "spicy", text: "Qual é a tua maior tentação quando estamos separados?", type: "text", options: [] },
  { id: 278, cat: "travel", text: "Se pudéssemos fazer uma viagem de comboio épica, qual escolhias?", type: "choice", options: ["Transiberiano (Rússia)", "Orient Express (Europa)", "Comboio pelo Sri Lanka", "Glacier Express (Suíça)"] },
  { id: 279, cat: "personality", text: "Preferes perdoar e esquecer ou perdoar mas nunca esquecer?", type: "thisorthat", options: ["Perdoar e esquecer", "Perdoar mas nunca esquecer"] },
  { id: 280, cat: "memories", text: "Qual foi a mensagem minha que te fez sorrir mais?", type: "text", options: [] },
  { id: 281, cat: "whatif", text: "Se eu te pedisse para largar tudo e irmos viver para uma ilha, aceitavas?", type: "thisorthat", options: ["Sim, sem pensar duas vezes", "Não, sou demasiado prático/a"] },
  { id: 282, cat: "us", text: "O que é que eu faço que te mostra que te amo sem dizer palavras?", type: "text", options: [] },
  { id: 283, cat: "food", text: "Preferes gelado de fruta ou gelado de chocolate?", type: "thisorthat", options: ["Gelado de fruta", "Gelado de chocolate"] },
  { id: 284, cat: "entertainment", text: "Qual é o teu vídeo do YouTube favorito de sempre?", type: "text", options: [] },
  { id: 285, cat: "spicy", text: "Achas que temos a mesma libido ou é desequilibrada?", type: "choice", options: ["A mesma, estamos em sintonia", "Eu tenho mais", "Tu tens mais", "Depende da fase"] },

  // === BATCH 20 (286-300) ===
  { id: 286, cat: "dreams", text: "Se pudéssemos criar uma fundação de caridade, que causa apoiávamos?", type: "text", options: [] },
  { id: 287, cat: "personality", text: "Qual é a coisa sobre ti que as pessoas costumam perceber mal?", type: "text", options: [] },
  { id: 288, cat: "intimacy", text: "O que é mais íntimo para ti: sexo ou dormir nos braços um do outro?", type: "thisorthat", options: ["Sexo", "Dormir nos braços um do outro"] },
  { id: 289, cat: "travel", text: "Se pudéssemos fazer mergulho juntos algures no mundo, onde seria?", type: "choice", options: ["Grande Barreira de Coral", "Maldivas", "Açores", "Tailândia"] },
  { id: 290, cat: "preferences", text: "Preferes um chuveiro rápido ou um banho demorado de banheira?", type: "thisorthat", options: ["Chuveiro rápido", "Banho de banheira"] },
  { id: 291, cat: "us", text: "Se tivéssemos uma playlist da nossa relação, que música abria?", type: "text", options: [] },
  { id: 292, cat: "spicy", text: "Se eu te pedisse para me dizer três coisas que não gostas em mim, o que dizias?", type: "text", options: [] },
  { id: 293, cat: "food", text: "Qual é o teu lanche ideal para uma sessão de filmes?", type: "choice", options: ["Pipocas doces", "Pipocas salgadas", "Nachos com guacamole", "Gelado e bolachas"] },
  { id: 294, cat: "memories", text: "Qual foi o Dia dos Namorados mais especial que passámos?", type: "text", options: [] },
  { id: 295, cat: "entertainment", text: "Preferes binge-watch ou ver um episódio por dia?", type: "thisorthat", options: ["Binge-watch total", "Um episódio por dia"] },
  { id: 296, cat: "whatif", text: "Se pudéssemos ter uma cópia exata um do outro como robot, aceitavas?", type: "thisorthat", options: ["Que ideia assustadora, não", "Seria interessante experimentar"] },
  { id: 297, cat: "personality", text: "Achas que sou mais teimoso/a ou flexível?", type: "thisorthat", options: ["Mais teimoso/a", "Mais flexível"] },
  { id: 298, cat: "dreams", text: "Qual é o sonho mais louco que tens e que nunca contaste a ninguém?", type: "text", options: [] },
  { id: 299, cat: "intimacy", text: "Qual é o toque meu que te acalma mais?", type: "text", options: [] },
  { id: 300, cat: "spicy", text: "Já te arrependeste de algo que me disseste numa discussão?", type: "thisorthat", options: ["Sim, arrependo-me", "Não, disse o que sentia"] },

  // === BATCH 21 (301-315) ===
  { id: 301, cat: "us", text: "Qual é a coisa que aprendi contigo que mais te surpreende?", type: "text", options: [] },
  { id: 302, cat: "food", text: "Preferes um pequeno-almoço continental ou um full English breakfast?", type: "thisorthat", options: ["Continental", "Full English breakfast"] },
  { id: 303, cat: "travel", text: "Se pudéssemos viver 3 meses em qualquer praia do mundo, qual escolhias?", type: "text", options: [] },
  { id: 304, cat: "entertainment", text: "Qual é o videojogo que te marcou na infância?", type: "text", options: [] },
  { id: 305, cat: "personality", text: "Qual é a tua reação quando alguém te decepciona?", type: "choice", options: ["Confronto diretamente", "Afasto-me em silêncio", "Dou uma segunda chance", "Finjo que não aconteceu"] },
  { id: 306, cat: "preferences", text: "Preferes pijama de flanela ou dormir com pouca roupa?", type: "thisorthat", options: ["Pijama de flanela", "Pouca roupa"] },
  { id: 307, cat: "spicy", text: "Qual é a coisa mais constrangedora que já pesquisaste no Google?", type: "text", options: [] },
  { id: 308, cat: "dreams", text: "Se pudéssemos deixar um legado juntos, qual seria?", type: "text", options: [] },
  { id: 309, cat: "intimacy", text: "Qual é o cenário romântico perfeito para ti?", type: "choice", options: ["Jantar à luz de velas", "Piquenique ao pôr do sol", "Banho de banheira a dois", "Noite debaixo das estrelas"] },
  { id: 310, cat: "memories", text: "Qual foi o momento em que percebeste que a distância valia a pena?", type: "text", options: [] },
  { id: 311, cat: "whatif", text: "Se tivéssemos que viver sem internet durante um mês, sobrevivíamos?", type: "thisorthat", options: ["Sim, seria libertador", "Não, seria impossível"] },
  { id: 312, cat: "us", text: "Que nota dás à nossa comunicação de 1 a 10?", type: "choice", options: ["10 - Perfeita", "8-9 - Muito boa", "6-7 - Boa mas pode melhorar", "Abaixo de 6 - Precisamos de trabalhar"] },
  { id: 313, cat: "food", text: "Qual é a comida de rua que mais gostavas de experimentar?", type: "choice", options: ["Tacos mexicanos autênticos", "Ramen japonês", "Pad Thai na Tailândia", "Churros em Madrid"] },
  { id: 314, cat: "personality", text: "Preferes ser a pessoa que se importa demais ou que se importa de menos?", type: "thisorthat", options: ["Importar-me demais", "Importar-me de menos"] },
  { id: 315, cat: "spicy", text: "Qual é a parte do meu passado que te custa mais aceitar?", type: "text", options: [] },

  // === BATCH 22 (316-330) ===
  { id: 316, cat: "travel", text: "Preferes uma semana nos Alpes suíços ou uma semana na costa amalfitana?", type: "thisorthat", options: ["Alpes suíços", "Costa amalfitana"] },
  { id: 317, cat: "intimacy", text: "O que posso fazer mais para manter a chama acesa à distância?", type: "text", options: [] },
  { id: 318, cat: "entertainment", text: "Qual é o concerto que gostavas de ter ido e nunca foste?", type: "text", options: [] },
  { id: 319, cat: "dreams", text: "Imaginas-te a viver no estrangeiro para sempre ou a voltar a Portugal?", type: "thisorthat", options: ["No estrangeiro para sempre", "Voltar a Portugal"] },
  { id: 320, cat: "us", text: "Qual é a diferença entre nós que mais te complementa?", type: "text", options: [] },
  { id: 321, cat: "preferences", text: "Preferes um carro desportivo ou um SUV confortável?", type: "thisorthat", options: ["Carro desportivo", "SUV confortável"] },
  { id: 322, cat: "spicy", text: "Se tivesses que classificar a minha aparência de 1 a 10, que nota davas?", type: "choice", options: ["10 sem dúvida", "9 - Quase perfeito/a", "8 - Muito atraente", "Não vou responder a isso"] },
  { id: 323, cat: "food", text: "Qual é o vinho que mais gostas de beber comigo?", type: "text", options: [] },
  { id: 324, cat: "memories", text: "Qual é o áudio ou mensagem de voz meu/minha que guardas?", type: "text", options: [] },
  { id: 325, cat: "personality", text: "Qual destas situações sociais te incomoda mais?", type: "choice", options: ["Festas com desconhecidos", "Jantares formais", "Ser o centro das atenções", "Small talk forçado"] },
  { id: 326, cat: "whatif", text: "Se ganhássemos uma casa em qualquer país, onde seria?", type: "text", options: [] },
  { id: 327, cat: "intimacy", text: "Preferes iniciar a intimidade ou que eu tome a iniciativa?", type: "thisorthat", options: ["Eu inicio", "Prefiro que tu inicies"] },
  { id: 328, cat: "us", text: "Qual é a coisa que mais te orgulha na nossa relação?", type: "text", options: [] },
  { id: 329, cat: "food", text: "Preferes um churrasco no jardim ou um fondue romântico?", type: "thisorthat", options: ["Churrasco no jardim", "Fondue romântico"] },
  { id: 330, cat: "spicy", text: "Achas que tenho ciúmes a mais, de menos, ou na medida certa?", type: "choice", options: ["Ciúmes a mais", "Ciúmes de menos", "Na medida certa", "Depende da situação"] },

  // === BATCH 23 (331-345) ===
  { id: 331, cat: "dreams", text: "Se pudéssemos criar uma empresa juntos, em que área seria?", type: "text", options: [] },
  { id: 332, cat: "personality", text: "Achas que sou uma pessoa que guarda rancor?", type: "thisorthat", options: ["Sim, um pouco", "Não, perdoas facilmente"] },
  { id: 333, cat: "travel", text: "Qual é o sítio mais romântico onde já estivemos juntos?", type: "text", options: [] },
  { id: 334, cat: "entertainment", text: "Se pudéssemos atuar num filme juntos, que género seria?", type: "choice", options: ["Romance épico", "Comédia de ação", "Thriller psicológico", "Musical"] },
  { id: 335, cat: "preferences", text: "Preferes uma tatuagem significativa ou nenhuma tatuagem?", type: "thisorthat", options: ["Tatuagem significativa", "Nenhuma tatuagem"] },
  { id: 336, cat: "us", text: "Quando estamos juntos, qual é o momento do dia que mais gostas?", type: "choice", options: ["Acordar juntos", "Almoço descontraído", "Passeio ao fim de tarde", "Adormecer abraçados"] },
  { id: 337, cat: "spicy", text: "Qual é a coisa que eu faço na cama que mais te agrada?", type: "text", options: [] },
  { id: 338, cat: "food", text: "Se tivéssemos que sobreviver com 3 alimentos para sempre, quais escolhias?", type: "text", options: [] },
  { id: 339, cat: "memories", text: "Qual foi a discussão nossa que, olhando para trás, foi completamente ridícula?", type: "text", options: [] },
  { id: 340, cat: "intimacy", text: "Preferes massagens longas ou beijos no pescoço?", type: "thisorthat", options: ["Massagens longas", "Beijos no pescoço"] },
  { id: 341, cat: "whatif", text: "Se pudéssemos falar com animais, qual era o primeiro que escolhias?", type: "choice", options: ["O teu cão/gato", "Um golfinho", "Uma águia", "Um gato de rua"] },
  { id: 342, cat: "personality", text: "Qual é a decisão mais difícil que já tomaste na vida?", type: "text", options: [] },
  { id: 343, cat: "dreams", text: "Se pudéssemos ter uma casa de férias, onde seria?", type: "choice", options: ["Algarve", "Açores", "Sul de França", "Grécia"] },
  { id: 344, cat: "travel", text: "Preferes viagens curtas frequentes ou uma viagem longa por ano?", type: "thisorthat", options: ["Viagens curtas frequentes", "Uma viagem longa por ano"] },
  { id: 345, cat: "spicy", text: "Se eu flirtasse com alguém à tua frente em tom de brincadeira, como reagias?", type: "choice", options: ["Não me importava nada", "Ficava incomodado/a por dentro", "Dizia-te alguma coisa depois", "Ficava furioso/a no momento"] },

  // === BATCH 24 (346-360) ===
  { id: 346, cat: "food", text: "Preferes um açaí bowl ou uma granola com iogurte?", type: "thisorthat", options: ["Açaí bowl", "Granola com iogurte"] },
  { id: 347, cat: "us", text: "Qual é a regra não escrita da nossa relação?", type: "text", options: [] },
  { id: 348, cat: "entertainment", text: "Se pudéssemos ir a um espetáculo na Broadway, qual escolhias?", type: "choice", options: ["Hamilton", "O Fantasma da Ópera", "O Rei Leão", "Wicked"] },
  { id: 349, cat: "intimacy", text: "O que é que mais adoras no nosso abraço?", type: "text", options: [] },
  { id: 350, cat: "personality", text: "Consideras-te uma pessoa de hábitos ou gostas de mudar constantemente?", type: "thisorthat", options: ["Pessoa de hábitos", "Gosto de mudar"] },
  { id: 351, cat: "dreams", text: "Se pudesses escrever um livro sobre nós, como seria o título?", type: "text", options: [] },
  { id: 352, cat: "spicy", text: "Achas que os teus amigos gostam genuinamente de mim?", type: "choice", options: ["Sim, adoram-te", "A maioria sim", "Alguns têm reservas", "Não tenho a certeza"] },
  { id: 353, cat: "travel", text: "Se pudéssemos fazer um safari juntos, onde seria?", type: "choice", options: ["Quénia", "Tanzânia", "África do Sul", "Botswana"] },
  { id: 354, cat: "memories", text: "Qual é a fotografia nossa que escolherias para emoldurar?", type: "text", options: [] },
  { id: 355, cat: "preferences", text: "Preferes uma casa com muita luz natural ou um ambiente mais escurinho e acolhedor?", type: "thisorthat", options: ["Muita luz natural", "Ambiente escurinho e acolhedor"] },
  { id: 356, cat: "whatif", text: "Se pudéssemos trocar de corpo por um dia, o que fazias no meu corpo?", type: "text", options: [] },
  { id: 357, cat: "food", text: "Qual é o cocktail que mais gostavas de beber comigo numa praia tropical?", type: "text", options: [] },
  { id: 358, cat: "personality", text: "Achas que mudei muito desde que estás comigo?", type: "thisorthat", options: ["Sim, mudaste bastante", "Não, és o/a mesmo/a na essência"] },
  { id: 359, cat: "us", text: "O que é que eu digo que te chateia mas nunca me disseste?", type: "text", options: [] },
  { id: 360, cat: "spicy", text: "Já tiveste curiosidade de ver as minhas mensagens sem eu saber?", type: "thisorthat", options: ["Sim, mas nunca vi", "Não, confio em ti completamente"] },

  // === BATCH 25 (361-375) ===
  { id: 361, cat: "entertainment", text: "Qual é o filme que te faz chorar sempre que vês?", type: "text", options: [] },
  { id: 362, cat: "intimacy", text: "Se pudéssemos passar o dia inteiro na cama, o que fazíamos?", type: "text", options: [] },
  { id: 363, cat: "dreams", text: "Se o mundo acabasse amanhã, como passavas o último dia?", type: "text", options: [] },
  { id: 364, cat: "travel", text: "Preferes um cruzeiro pelo Nilo ou uma viagem de mochila pela Ásia?", type: "thisorthat", options: ["Cruzeiro pelo Nilo", "Mochila pela Ásia"] },
  { id: 365, cat: "preferences", text: "Preferes um perfume forte e marcante ou algo suave e discreto?", type: "thisorthat", options: ["Forte e marcante", "Suave e discreto"] },
  { id: 366, cat: "us", text: "Qual é a fase da nossa relação que foi a mais bonita?", type: "text", options: [] },
  { id: 367, cat: "spicy", text: "Qual é a coisa que mais te excita em mim que nunca me disseste?", type: "text", options: [] },
  { id: 368, cat: "food", text: "Preferes comer saudável a semana toda ou ter cheat meals?", type: "thisorthat", options: ["Saudável a semana toda", "Cheat meals são essenciais"] },
  { id: 369, cat: "personality", text: "Achas que sou uma pessoa fácil de amar?", type: "choice", options: ["Sim, muito fácil", "Sim, mas tens os teus momentos", "Nem sempre é fácil", "Amo-te mas desafias-me"] },
  { id: 370, cat: "memories", text: "Qual é o presente que te dei e que mais significou para ti?", type: "text", options: [] },
  { id: 371, cat: "whatif", text: "Se pudesses ter jantar com 3 pessoas famosas, quem escolhias?", type: "text", options: [] },
  { id: 372, cat: "food", text: "Qual é a tua combinação de comida mais estranha que adoras?", type: "text", options: [] },
  { id: 373, cat: "entertainment", text: "Se pudéssemos criar um canal de YouTube juntos, sobre o que seria?", type: "choice", options: ["Viagens e aventuras", "Culinária para casais", "Vlogs diários", "Challenges e brincadeiras"] },
  { id: 374, cat: "intimacy", text: "Qual é o tipo de roupa que mais gostas de me ver vestido/a?", type: "text", options: [] },
  { id: 375, cat: "spicy", text: "Se pudesses mudar uma coisa na nossa vida sexual, o que seria?", type: "text", options: [] },

  // === BATCH 26 (376-390) ===
  { id: 376, cat: "us", text: "Achas que estamos a crescer juntos ou em paralelo?", type: "thisorthat", options: ["A crescer juntos", "A crescer em paralelo"] },
  { id: 377, cat: "dreams", text: "Se pudéssemos ter uma cabana nas montanhas, como a decoravas?", type: "text", options: [] },
  { id: 378, cat: "travel", text: "Qual é o aeroporto ou estação onde tivemos a despedida mais difícil?", type: "text", options: [] },
  { id: 379, cat: "food", text: "Se pudéssemos ter um piquenique perfeito, o que levávamos?", type: "text", options: [] },
  { id: 380, cat: "personality", text: "Qual é a coisa sobre mim que os outros não veem mas tu vês?", type: "text", options: [] },
  { id: 381, cat: "preferences", text: "Preferes uma cama king-size ou uma cama mais pequena para estar mais juntinhos?", type: "thisorthat", options: ["King-size", "Mais pequena para estarmos juntos"] },
  { id: 382, cat: "spicy", text: "Já sentiste que dás mais à relação do que eu?", type: "thisorthat", options: ["Sim, às vezes sinto", "Não, é equilibrado"] },
  { id: 383, cat: "entertainment", text: "Preferes um espetáculo de magia ou um espetáculo de circo?", type: "thisorthat", options: ["Espetáculo de magia", "Espetáculo de circo"] },
  { id: 384, cat: "memories", text: "Qual foi o reencontro nosso que mais te emocionou?", type: "text", options: [] },
  { id: 385, cat: "intimacy", text: "Preferes luzes acesas ou apagadas?", type: "thisorthat", options: ["Luzes acesas", "Luzes apagadas"] },
  { id: 386, cat: "whatif", text: "Se pudéssemos inventar um feriado só nosso, como seria?", type: "text", options: [] },
  { id: 387, cat: "personality", text: "Quando estás sozinho/a, em que pensas mais?", type: "choice", options: ["No futuro", "Nas memórias", "Nos problemas atuais", "Em coisas aleatórias"] },
  { id: 388, cat: "dreams", text: "Se pudéssemos gravar um álbum de música juntos, que estilo seria?", type: "choice", options: ["Acústico e romântico", "Pop animado", "Jazz suave", "Indie alternativo"] },
  { id: 389, cat: "us", text: "Qual é a tradição de casal que queres que nunca acabe?", type: "text", options: [] },
  { id: 390, cat: "spicy", text: "Achas que eu sou o/a melhor parceiro/a que já tiveste? Sê honesto/a.", type: "choice", options: ["Sim, sem dúvida", "Sim, na maioria dos aspetos", "Em algumas coisas sim, noutras não", "Prefiro não comparar"] },

  // === BATCH 27 (391-405) ===
  { id: 391, cat: "food", text: "Preferes um pastel de nata quentinho ou um croissant acabado de fazer?", type: "thisorthat", options: ["Pastel de nata quentinho", "Croissant acabado de fazer"] },
  { id: 392, cat: "travel", text: "Se pudéssemos ir à lua de mel amanhã, para onde íamos?", type: "choice", options: ["Bali", "Maldivas", "Santorini", "Seychelles"] },
  { id: 393, cat: "personality", text: "Qual é a tua maior insegurança pessoal?", type: "text", options: [] },
  { id: 394, cat: "entertainment", text: "Se pudéssemos assistir a qualquer evento desportivo, qual escolhias?", type: "choice", options: ["Final da Champions League", "Super Bowl", "Jogos Olímpicos", "Final de Wimbledon"] },
  { id: 395, cat: "preferences", text: "Preferes usar o dinheiro em experiências ou em coisas materiais?", type: "thisorthat", options: ["Experiências", "Coisas materiais"] },
  { id: 396, cat: "us", text: "Se pudéssemos recomeçar como amigos e reconstruir a relação, fazias tudo igual?", type: "thisorthat", options: ["Sim, tudo igual", "Mudava algumas coisas"] },
  { id: 397, cat: "spicy", text: "Qual é a coisa que faço inconscientemente que te irrita profundamente?", type: "text", options: [] },
  { id: 398, cat: "memories", text: "Qual foi o momento em que sentiste mais medo de me perder?", type: "text", options: [] },
  { id: 399, cat: "dreams", text: "Como imaginas o nosso Natal daqui a 20 anos?", type: "text", options: [] },
  { id: 400, cat: "intimacy", text: "Qual é a coisa mais romântica que alguém pode fazer por ti?", type: "text", options: [] },
  { id: 401, cat: "whatif", text: "Se eu te dissesse que queria mudar radicalmente de visual, apoiavas?", type: "choice", options: ["Apoiava a 100%", "Depende da mudança", "Dava a minha opinião honesta", "Ficaria preocupado/a"] },
  { id: 402, cat: "food", text: "Qual é a comida que comes quando ninguém está a ver?", type: "text", options: [] },
  { id: 403, cat: "personality", text: "Achas que tens mais paciência ou impaciência?", type: "thisorthat", options: ["Mais paciência", "Mais impaciência"] },
  { id: 404, cat: "travel", text: "Se pudéssemos alugar uma casa em frente ao mar durante um mês, onde seria?", type: "text", options: [] },
  { id: 405, cat: "spicy", text: "Qual é a coisa sobre ex-relações que ainda afeta a forma como ages comigo?", type: "text", options: [] },

  // === BATCH 28 (406-420) ===
  { id: 406, cat: "us", text: "Se pudéssemos escrever votos um ao outro agora, o que dirias?", type: "text", options: [] },
  { id: 407, cat: "entertainment", text: "Preferes um musical ao vivo ou um concerto de rock?", type: "thisorthat", options: ["Musical ao vivo", "Concerto de rock"] },
  { id: 408, cat: "dreams", text: "Qual é o projeto pessoal que gostavas de concretizar nos próximos 2 anos?", type: "text", options: [] },
  { id: 409, cat: "preferences", text: "Preferes uma camisola confortável velha ou roupa nova estilosa?", type: "thisorthat", options: ["Camisola confortável velha", "Roupa nova estilosa"] },
  { id: 410, cat: "food", text: "Se pudéssemos ter um jantar temático, que cozinha do mundo escolhias?", type: "choice", options: ["Indiana", "Peruana", "Coreana", "Marroquina"] },
  { id: 411, cat: "personality", text: "Qual é a coisa que mais te orgulha em ti?", type: "text", options: [] },
  { id: 412, cat: "spicy", text: "Há alguma coisa que eu faço que te faz questionar se sou a pessoa certa?", type: "text", options: [] },
  { id: 413, cat: "travel", text: "Se pudéssemos fazer um retiro espiritual juntos, onde seria?", type: "choice", options: ["Bali", "Índia", "Nepal", "Peru"] },
  { id: 414, cat: "intimacy", text: "Qual é a forma como demonstras amor que achas que eu não noto?", type: "text", options: [] },
  { id: 415, cat: "memories", text: "Qual foi o momento mais espontâneo e bonito que vivemos?", type: "text", options: [] },
  { id: 416, cat: "whatif", text: "Se pudéssemos viver a vida de um casal famoso por uma semana, quem escolhias?", type: "text", options: [] },
  { id: 417, cat: "us", text: "Preferes que sejamos o casal mais engraçado ou o mais romântico do grupo?", type: "thisorthat", options: ["O mais engraçado", "O mais romântico"] },
  { id: 418, cat: "food", text: "Preferes um café expresso forte ou um café com leite cremoso?", type: "thisorthat", options: ["Expresso forte", "Café com leite cremoso"] },
  { id: 419, cat: "personality", text: "Qual é a coisa que achas mais difícil de comunicar em qualquer relação?", type: "choice", options: ["Necessidades emocionais", "Limites pessoais", "Insatisfação", "Medos e inseguranças"] },
  { id: 420, cat: "spicy", text: "Se pudesses saber quantas pessoas me acham atraente, querias saber?", type: "thisorthat", options: ["Sim, por curiosidade", "Não, prefiro não saber"] },

  // === BATCH 29 (421-435) ===
  { id: 421, cat: "dreams", text: "Se pudéssemos viver sem preocupações financeiras, como seria o nosso dia-a-dia?", type: "text", options: [] },
  { id: 422, cat: "travel", text: "Preferes visitar ruínas antigas ou cidades futurísticas?", type: "thisorthat", options: ["Ruínas antigas", "Cidades futurísticas"] },
  { id: 423, cat: "entertainment", text: "Qual é a cena de filme que mais te arrepia?", type: "text", options: [] },
  { id: 424, cat: "intimacy", text: "Qual é a coisa mais íntima que partilhamos que não é física?", type: "text", options: [] },
  { id: 425, cat: "preferences", text: "Preferes um bom livro ou uma boa conversa?", type: "thisorthat", options: ["Um bom livro", "Uma boa conversa"] },
  { id: 426, cat: "us", text: "Se eu te surpreendesse com uma viagem, para onde gostarias que fosse?", type: "text", options: [] },
  { id: 427, cat: "spicy", text: "Qual é a coisa sobre a qual mais evitamos falar?", type: "text", options: [] },
  { id: 428, cat: "food", text: "Qual é o prato que fazemos juntos que fica sempre bem?", type: "text", options: [] },
  { id: 429, cat: "personality", text: "Qual destas qualidades valorizas mais num parceiro/a?", type: "choice", options: ["Inteligência", "Sentido de humor", "Bondade", "Ambição"] },
  { id: 430, cat: "memories", text: "Qual foi a primeira vez que nos abraçámos e como te sentiste?", type: "text", options: [] },
  { id: 431, cat: "whatif", text: "Se pudéssemos ter um poder sobre o tempo, o que fazias?", type: "choice", options: ["Parar o tempo nos melhores momentos", "Voltar atrás e corrigir erros", "Avançar para ver o futuro", "Viver tudo em câmara lenta"] },
  { id: 432, cat: "dreams", text: "Se pudéssemos adotar uma tradição de outro país, qual seria?", type: "text", options: [] },
  { id: 433, cat: "food", text: "Preferes um shot de tequila ou um copo de vinho do Porto?", type: "thisorthat", options: ["Shot de tequila", "Vinho do Porto"] },
  { id: 434, cat: "travel", text: "Qual é o aeroporto do mundo que mais gostavas de conhecer?", type: "choice", options: ["Changi (Singapura)", "Hamad (Doha)", "Haneda (Tóquio)", "Schiphol (Amesterdão)"] },
  { id: 435, cat: "spicy", text: "Já te sentiste sufocado/a na nossa relação?", type: "thisorthat", options: ["Sim, em certos momentos", "Não, nunca"] },

  // === BATCH 30 (436-450) ===
  { id: 436, cat: "personality", text: "Qual é a coisa que mais mudou em ti desde que estamos juntos?", type: "text", options: [] },
  { id: 437, cat: "intimacy", text: "Qual é a hora do dia em que te sentes mais romântico/a?", type: "choice", options: ["De manhã cedo", "Ao fim da tarde", "Depois do jantar", "Tarde da noite"] },
  { id: 438, cat: "us", text: "Se pudéssemos renovar uma promessa um ao outro, qual seria?", type: "text", options: [] },
  { id: 439, cat: "entertainment", text: "Qual é o podcast ou canal que devíamos ouvir juntos?", type: "text", options: [] },
  { id: 440, cat: "preferences", text: "Preferes uma escapadinha no campo ou na cidade?", type: "thisorthat", options: ["No campo", "Na cidade"] },
  { id: 441, cat: "memories", text: "Qual foi o momento em que te sentiste mais vulnerável comigo?", type: "text", options: [] },
  { id: 442, cat: "spicy", text: "Se eu mudasse completamente de personalidade, ainda me amavas?", type: "choice", options: ["Sim, amor é incondicional", "Depende da mudança", "Provavelmente não", "Não sei, é uma pergunta difícil"] },
  { id: 443, cat: "food", text: "Qual é a comida que associas a momentos felizes da tua infância?", type: "text", options: [] },
  { id: 444, cat: "dreams", text: "Se pudéssemos ter um superpoder como casal, qual seria?", type: "choice", options: ["Teletransporte para estar sempre juntos", "Ler os pensamentos um do outro", "Parar o tempo quando estamos juntos", "Curar qualquer doença com um abraço"] },
  { id: 445, cat: "travel", text: "Preferes ver a aurora boreal ou o pôr do sol em Santorini?", type: "thisorthat", options: ["Aurora boreal", "Pôr do sol em Santorini"] },
  { id: 446, cat: "whatif", text: "Se pudéssemos voltar a ser crianças por um dia juntos, o que fazíamos?", type: "text", options: [] },
  { id: 447, cat: "personality", text: "Qual é a coisa que gostavas de ter aprendido mais cedo na vida?", type: "text", options: [] },
  { id: 448, cat: "us", text: "Se tivéssemos que descrever a nossa relação com uma cor, qual seria?", type: "text", options: [] },
  { id: 449, cat: "intimacy", text: "Preferes palavras doces ao ouvido ou olhares intensos?", type: "thisorthat", options: ["Palavras doces ao ouvido", "Olhares intensos"] },
  { id: 450, cat: "spicy", text: "Se pudesses apagar uma memória nossa, qual apagavas?", type: "text", options: [] },

  // === BATCH 31 (451-465) ===
  { id: 451, cat: "food", text: "Qual é a comida que parece nojenta mas que adoras secretamente?", type: "text", options: [] },
  { id: 452, cat: "entertainment", text: "Se pudéssemos estar na plateia de qualquer talk show, qual escolhias?", type: "choice", options: ["The Graham Norton Show", "Hot Ones", "Joe Rogan", "Um programa português"] },
  { id: 453, cat: "travel", text: "Qual é a experiência de viagem que temos de fazer antes dos 40?", type: "text", options: [] },
  { id: 454, cat: "preferences", text: "Preferes música alta para dançar ou música baixa para conversar?", type: "thisorthat", options: ["Música alta para dançar", "Música baixa para conversar"] },
  { id: 455, cat: "us", text: "Qual foi o sacrifício mais difícil que fizeste pela nossa relação?", type: "text", options: [] },
  { id: 456, cat: "personality", text: "Qual é o teu traço de personalidade mais forte?", type: "choice", options: ["Determinação", "Empatia", "Criatividade", "Resiliência"] },
  { id: 457, cat: "spicy", text: "Se eu te dissesse que queria experimentar algo novo na intimidade, qual seria a tua reação?", type: "choice", options: ["Aberto/a a tudo", "Depende do que fosse", "Ficaria desconfortável", "Ficaria curioso/a e entusiasmado/a"] },
  { id: 458, cat: "dreams", text: "Se pudéssemos fazer um documentário sobre a nossa história, como seria o título?", type: "text", options: [] },
  { id: 459, cat: "intimacy", text: "Qual é a coisa que mais sentes falta quando estamos separados fisicamente?", type: "choice", options: ["O teu cheiro", "O teu abraço", "Dormir juntos", "Os beijos"] },
  { id: 460, cat: "memories", text: "Qual é o sítio onde nos encontrámos pela primeira vez que nunca vais esquecer?", type: "text", options: [] },
  { id: 461, cat: "whatif", text: "Se o mundo parasse e só restássemos nós dois, o que fazias primeiro?", type: "text", options: [] },
  { id: 462, cat: "food", text: "Preferes um brunch tardio ao domingo ou uma ceia à meia-noite?", type: "thisorthat", options: ["Brunch tardio ao domingo", "Ceia à meia-noite"] },
  { id: 463, cat: "personality", text: "Achas que mudas de opinião facilmente ou manténs as tuas posições?", type: "thisorthat", options: ["Mudo facilmente", "Mantenho as minhas posições"] },
  { id: 464, cat: "travel", text: "Preferes uma viagem organizada por uma agência ou planeada por nós?", type: "thisorthat", options: ["Organizada por agência", "Planeada por nós"] },
  { id: 465, cat: "spicy", text: "Se pudesses ver uma conversa minha com alguém sem eu saber, de quem escolhias?", type: "text", options: [] },

  // === BATCH 32 (466-480) ===
  { id: 466, cat: "us", text: "Se pudéssemos gravar um vídeo para o nosso eu do futuro, o que dizias?", type: "text", options: [] },
  { id: 467, cat: "entertainment", text: "Preferes uma noite de cinema em casa com pipocas ou um drive-in?", type: "thisorthat", options: ["Cinema em casa", "Drive-in"] },
  { id: 468, cat: "dreams", text: "Se pudéssemos criar a vida perfeita juntos sem limitações, como seria um dia típico?", type: "text", options: [] },
  { id: 469, cat: "preferences", text: "Preferes resolver conflitos por mensagem ou cara a cara?", type: "thisorthat", options: ["Por mensagem", "Cara a cara"] },
  { id: 470, cat: "food", text: "Qual é o prato estrangeiro que descobriste e agora adoras?", type: "text", options: [] },
  { id: 471, cat: "personality", text: "Qual é a emoção que sentes com mais frequência mas escondes?", type: "choice", options: ["Ansiedade", "Tristeza", "Frustração", "Solidão"] },
  { id: 472, cat: "spicy", text: "Se tivesses que escolher entre perder a memória comigo ou manter todas as memórias mas nunca mais me ver, o que escolhias?", type: "thisorthat", options: ["Perder a memória mas estar contigo", "Manter memórias mas nunca mais te ver"] },
  { id: 473, cat: "travel", text: "Qual é o hotel ou alojamento dos nossos sonhos para uma ocasião especial?", type: "text", options: [] },
  { id: 474, cat: "intimacy", text: "Qual é a promessa que queres que eu te faça e nunca quebre?", type: "text", options: [] },
  { id: 475, cat: "memories", text: "Qual foi o momento em que chorámos juntos e que nos aproximou?", type: "text", options: [] },
  { id: 476, cat: "whatif", text: "Se pudéssemos viver numa série de TV, qual escolhias?", type: "choice", options: ["Friends", "How I Met Your Mother", "The Office", "Outra"] },
  { id: 477, cat: "us", text: "O que significo eu para ti em 3 palavras?", type: "text", options: [] },
  { id: 478, cat: "food", text: "Preferes um jantar à luz de velas em casa ou uma tasca portuguesa?", type: "thisorthat", options: ["Jantar à luz de velas em casa", "Tasca portuguesa"] },
  { id: 479, cat: "personality", text: "Qual é a lição mais importante que a nossa relação te ensinou?", type: "text", options: [] },
  { id: 480, cat: "spicy", text: "Já duvidaste dos meus sentimentos por ti? Se sim, quando?", type: "text", options: [] },

  // === BATCH 33 (481-495) ===
  { id: 481, cat: "dreams", text: "Se pudéssemos ter um final de conto de fadas, como seria?", type: "text", options: [] },
  { id: 482, cat: "entertainment", text: "Qual é a música que dançarias comigo no nosso casamento?", type: "text", options: [] },
  { id: 483, cat: "preferences", text: "Preferes uma vida simples e tranquila ou uma vida intensa e cheia de aventuras?", type: "thisorthat", options: ["Simples e tranquila", "Intensa e cheia de aventuras"] },
  { id: 484, cat: "travel", text: "Se pudéssemos fazer o Caminho de Santiago juntos, faríamos?", type: "thisorthat", options: ["Sim, seria incrível", "Não é bem a minha cena"] },
  { id: 485, cat: "us", text: "Qual é a frase minha que guardas no coração?", type: "text", options: [] },
  { id: 486, cat: "intimacy", text: "Qual é o momento mais bonito de vulnerabilidade que partilhámos?", type: "text", options: [] },
  { id: 487, cat: "spicy", text: "Se tivéssemos que passar um mês sem qualquer contacto, sobrevivíamos como casal?", type: "thisorthat", options: ["Sim, somos fortes o suficiente", "Seria muito difícil"] },
  { id: 488, cat: "food", text: "Se pudéssemos ter aulas de culinária juntos, que cozinha aprendíamos?", type: "choice", options: ["Sushi e cozinha japonesa", "Pasta italiana fresca", "Pastelaria francesa", "Cozinha tailandesa"] },
  { id: 489, cat: "personality", text: "Achas que sou mais controlador/a ou descontraído/a?", type: "thisorthat", options: ["Mais controlador/a", "Mais descontraído/a"] },
  { id: 490, cat: "memories", text: "Qual é a conversa nossa que mais te marcou e porquê?", type: "text", options: [] },
  { id: 491, cat: "whatif", text: "Se pudéssemos deixar uma cápsula do tempo para os nossos netos, o que metíamos lá dentro?", type: "text", options: [] },
  { id: 492, cat: "dreams", text: "Qual é o lugar no mundo onde te imaginas a pedir-me em casamento ou a ser pedido/a?", type: "text", options: [] },
  { id: 493, cat: "entertainment", text: "Preferes que te leiam um livro em voz alta ou que te contem uma história original?", type: "thisorthat", options: ["Livro em voz alta", "História original"] },
  { id: 494, cat: "travel", text: "Se pudéssemos repetir uma viagem nossa, qual repetias?", type: "text", options: [] },
  { id: 495, cat: "spicy", text: "Qual é a verdade sobre nós que ninguém quer admitir mas que é real?", type: "text", options: [] },

  // === BATCH 34 (496-500) ===
  { id: 496, cat: "us", text: "Se pudéssemos prometer uma coisa um ao outro para sempre, o que prometias?", type: "text", options: [] },
  { id: 497, cat: "intimacy", text: "Qual é a tua definição pessoal de amor verdadeiro?", type: "text", options: [] },
  { id: 498, cat: "preferences", text: "Preferes envelhecer juntos calmamente ou manter sempre o espírito de aventura?", type: "thisorthat", options: ["Envelhecer calmamente juntos", "Manter o espírito de aventura"] },
  { id: 499, cat: "dreams", text: "Onde imaginas que vamos estar quando tivermos 80 anos?", type: "text", options: [] },
  { id: 500, cat: "spicy", text: "Se pudesses saber tudo sobre o futuro da nossa relação, querias saber?", type: "thisorthat", options: ["Sim, quero saber tudo", "Não, prefiro viver o momento"] }
];
