/* 500 Perguntas de Amor - José & Rita */
const QUESTIONS = [
// ===== CAT 0: Gostos & Preferências (1-50) =====
{id:1,cat:0,text:"Preferes um jantar romântico à luz de velas ou um piquenique ao pôr do sol?",type:"thisorthat",options:["Jantar à luz de velas","Piquenique ao pôr do sol"]},
{id:2,cat:0,text:"Preferes férias na praia ou férias na montanha?",type:"thisorthat",options:["Praia","Montanha"]},
{id:3,cat:0,text:"Preferes acordar cedo para ver o nascer do sol ou ficar acordado/a até tarde a ver estrelas?",type:"thisorthat",options:["Nascer do sol","Ver estrelas à noite"]},
{id:4,cat:0,text:"Preferes receber flores ou receber uma carta escrita à mão?",type:"thisorthat",options:["Flores","Carta escrita à mão"]},
{id:5,cat:0,text:"Preferes um domingo de sofá com filmes ou um domingo de aventura ao ar livre?",type:"thisorthat",options:["Sofá com filmes","Aventura ao ar livre"]},
{id:6,cat:0,text:"Preferes ouvir música ao vivo num concerto ou dançar numa festa privada a dois?",type:"thisorthat",options:["Concerto ao vivo","Festa privada a dois"]},
{id:7,cat:0,text:"Preferes um presente surpresa ou escolher o teu próprio presente?",type:"thisorthat",options:["Presente surpresa","Escolher o meu presente"]},
{id:8,cat:0,text:"Preferes viver numa cidade grande ou numa vila tranquila?",type:"thisorthat",options:["Cidade grande","Vila tranquila"]},
{id:9,cat:0,text:"Preferes ler um bom livro ou ver uma boa série?",type:"thisorthat",options:["Ler um livro","Ver uma série"]},
{id:10,cat:0,text:"Preferes cozinhar juntos em casa ou ir a um restaurante novo?",type:"thisorthat",options:["Cozinhar juntos","Restaurante novo"]},
{id:11,cat:0,text:"Preferes um abraço longo ou um beijo apaixonado?",type:"thisorthat",options:["Abraço longo","Beijo apaixonado"]},
{id:12,cat:0,text:"Preferes viajar de carro sem destino ou ter tudo planeado ao pormenor?",type:"thisorthat",options:["Sem destino","Tudo planeado"]},
{id:13,cat:0,text:"Preferes inverno com cobertor e chocolate quente ou verão com gelados e praia?",type:"thisorthat",options:["Inverno aconchegante","Verão na praia"]},
{id:14,cat:0,text:"Preferes dar presentes ou receber presentes?",type:"thisorthat",options:["Dar presentes","Receber presentes"]},
{id:15,cat:0,text:"Preferes uma casa com jardim ou um apartamento com vista?",type:"thisorthat",options:["Casa com jardim","Apartamento com vista"]},
{id:16,cat:0,text:"Preferes fotografias impressas num álbum ou fotografias digitais organizadas?",type:"thisorthat",options:["Álbum impresso","Fotografias digitais"]},
{id:17,cat:0,text:"Preferes um perfume doce ou um perfume fresco?",type:"thisorthat",options:["Perfume doce","Perfume fresco"]},
{id:18,cat:0,text:"Preferes uma festa de aniversário grande ou uma celebração íntima?",type:"thisorthat",options:["Festa grande","Celebração íntima"]},
{id:19,cat:0,text:"Preferes tomar o pequeno-almoço na cama ou numa esplanada?",type:"thisorthat",options:["Na cama","Numa esplanada"]},
{id:20,cat:0,text:"Preferes um animal de estimação (cão) ou um gato?",type:"thisorthat",options:["Cão","Gato"]},
{id:21,cat:0,text:"Preferes uma noite de jogos de tabuleiro ou uma noite de karaoke?",type:"thisorthat",options:["Jogos de tabuleiro","Karaoke"]},
{id:22,cat:0,text:"Preferes um banho quente relaxante ou um duche rápido e revigorante?",type:"thisorthat",options:["Banho quente relaxante","Duche revigorante"]},
{id:23,cat:0,text:"Preferes arte moderna ou arte clássica?",type:"thisorthat",options:["Arte moderna","Arte clássica"]},
{id:24,cat:0,text:"Preferes filmes de comédia ou filmes de drama?",type:"thisorthat",options:["Comédia","Drama"]},
{id:25,cat:0,text:"Preferes usar roupa confortável ou roupa elegante?",type:"thisorthat",options:["Roupa confortável","Roupa elegante"]},
{id:26,cat:0,text:"Qual é a tua estação do ano preferida?",type:"choice",options:["Primavera","Verão","Outono","Inverno"]},
{id:27,cat:0,text:"Que tipo de música te põe de melhor humor?",type:"choice",options:["Pop","Rock","Jazz/Blues","Música clássica"]},
{id:28,cat:0,text:"Como preferes passar uma noite livre?",type:"choice",options:["A ver filmes/séries","A ler","A sair com amigos","A fazer algo criativo"]},
{id:29,cat:0,text:"Qual é o teu tipo de férias ideal?",type:"choice",options:["Praia e resort","Cidade e cultura","Natureza e aventura","Road trip"]},
{id:30,cat:0,text:"O que mais valorizas num presente?",type:"choice",options:["O valor sentimental","A utilidade prática","A criatividade","A surpresa"]},
{id:31,cat:0,text:"Como preferes demonstrar carinho?",type:"choice",options:["Palavras","Gestos e ações","Contacto físico","Presentes e surpresas"]},
{id:32,cat:0,text:"Qual é o teu hobby de sonho que ainda não experimentaste?",type:"choice",options:["Pintura ou escultura","Tocar um instrumento","Desporto radical","Escrita criativa"]},
{id:33,cat:0,text:"Que tipo de filme escolherias para uma sessão de cinema a dois?",type:"choice",options:["Romance","Ação/Aventura","Comédia","Suspense/Thriller"]},
{id:34,cat:0,text:"Qual é o teu momento favorito do dia?",type:"choice",options:["Manhã cedo","Hora de almoço","Final da tarde","Noite"]},
{id:35,cat:0,text:"Se pudesses ter um superpoder, qual escolherias?",type:"choice",options:["Voar","Ler mentes","Teletransporte","Parar o tempo"]},
{id:36,cat:0,text:"O que te faz sentir mais relaxado/a?",type:"choice",options:["Ouvir música","Tomar um banho quente","Passear na natureza","Meditar ou ler"]},
{id:37,cat:0,text:"Que rede social usas mais?",type:"choice",options:["Instagram","TikTok","YouTube","Nenhuma em particular"]},
{id:38,cat:0,text:"De 1 a 10, quão importante é para ti ter tempo sozinho/a?",type:"scale",options:[]},
{id:39,cat:0,text:"De 1 a 10, quanto gostas de experimentar coisas novas?",type:"scale",options:[]},
{id:40,cat:0,text:"De 1 a 10, quão organizado/a te consideras?",type:"scale",options:[]},
{id:41,cat:0,text:"De 1 a 10, quanto gostas de festas e eventos sociais?",type:"scale",options:[]},
{id:42,cat:0,text:"De 1 a 10, quão aventureiro/a és quando se trata de viajar?",type:"scale",options:[]},
{id:43,cat:0,text:"De 1 a 10, quanto te influencia a opinião dos outros nas tuas decisões?",type:"scale",options:[]},
{id:44,cat:0,text:"De 1 a 10, quão nostálgico/a és?",type:"scale",options:[]},
{id:45,cat:0,text:"De 1 a 10, quanto gostas de rotinas diárias?",type:"scale",options:[]},
{id:46,cat:0,text:"Qual é a canção que mais te faz pensar em nós?",type:"text",options:[]},
{id:47,cat:0,text:"Se pudesses viver em qualquer país do mundo, qual escolherias e porquê?",type:"text",options:[]},
{id:48,cat:0,text:"Qual é o teu guilty pleasure secreto?",type:"text",options:[]},
{id:49,cat:0,text:"Descreve o teu dia perfeito em três palavras.",type:"text",options:[]},
{id:50,cat:0,text:"Qual é o pequeno gesto do dia a dia que mais te faz feliz?",type:"text",options:[]},
// ===== CAT 1: Sobre Nós (51-100) =====
{id:51,cat:1,text:"Quem de nós é mais teimoso/a?",type:"thisorthat",options:["Eu","Tu"]},
{id:52,cat:1,text:"Quem de nós disse 'eu amo-te' primeiro?",type:"thisorthat",options:["Eu","Tu"]},
{id:53,cat:1,text:"Quem de nós é mais ciumento/a?",type:"thisorthat",options:["Eu","Tu"]},
{id:54,cat:1,text:"Quem de nós demora mais a arranjar-se para sair?",type:"thisorthat",options:["Eu","Tu"]},
{id:55,cat:1,text:"Quem de nós é mais romântico/a?",type:"thisorthat",options:["Eu","Tu"]},
{id:56,cat:1,text:"Quem de nós manda mais mensagens durante o dia?",type:"thisorthat",options:["Eu","Tu"]},
{id:57,cat:1,text:"Quem de nós tem mais paciência?",type:"thisorthat",options:["Eu","Tu"]},
{id:58,cat:1,text:"Quem de nós cede primeiro numa discussão?",type:"thisorthat",options:["Eu","Tu"]},
{id:59,cat:1,text:"Quem de nós é mais carente de mimos?",type:"thisorthat",options:["Eu","Tu"]},
{id:60,cat:1,text:"Quem de nós é mais provável de chorar a ver um filme?",type:"thisorthat",options:["Eu","Tu"]},
{id:61,cat:1,text:"Quem de nós é o/a mais divertido/a?",type:"thisorthat",options:["Eu","Tu"]},
{id:62,cat:1,text:"Quem de nós escolhe sempre o restaurante?",type:"thisorthat",options:["Eu","Tu"]},
{id:63,cat:1,text:"Quem de nós é mais cabeça-no-ar?",type:"thisorthat",options:["Eu","Tu"]},
{id:64,cat:1,text:"Quem de nós fala mais ao telefone?",type:"thisorthat",options:["Eu","Tu"]},
{id:65,cat:1,text:"Quem de nós é mais difícil de acordar de manhã?",type:"thisorthat",options:["Eu","Tu"]},
{id:66,cat:1,text:"Quem de nós tem o riso mais contagiante?",type:"thisorthat",options:["Eu","Tu"]},
{id:67,cat:1,text:"Quem de nós é mais protetor/a?",type:"thisorthat",options:["Eu","Tu"]},
{id:68,cat:1,text:"Quem de nós gasta mais dinheiro?",type:"thisorthat",options:["Eu","Tu"]},
{id:69,cat:1,text:"Quem de nós é mais mandão/mandona?",type:"thisorthat",options:["Eu","Tu"]},
{id:70,cat:1,text:"Quem de nós faz mais surpresas?",type:"thisorthat",options:["Eu","Tu"]},
{id:71,cat:1,text:"Quem de nós é mais desastrado/a?",type:"thisorthat",options:["Eu","Tu"]},
{id:72,cat:1,text:"Quem de nós rouba mais a roupa do outro?",type:"thisorthat",options:["Eu","Tu"]},
{id:73,cat:1,text:"Quem de nós é melhor a guardar segredos?",type:"thisorthat",options:["Eu","Tu"]},
{id:74,cat:1,text:"Quem de nós tem sempre razão (ou pensa que tem)?",type:"thisorthat",options:["Eu","Tu"]},
{id:75,cat:1,text:"Quem de nós dá os melhores abraços?",type:"thisorthat",options:["Eu","Tu"]},
{id:76,cat:1,text:"Qual é a nossa maior qualidade enquanto casal?",type:"choice",options:["Comunicação","Cumplicidade","Diversão juntos","Apoio mútuo"]},
{id:77,cat:1,text:"Onde achas que funcionamos melhor juntos?",type:"choice",options:["Em viagens","No dia a dia","Em situações difíceis","Em momentos de diversão"]},
{id:78,cat:1,text:"Qual é o nosso programa de casal favorito?",type:"choice",options:["Jantar fora","Maratona de séries","Passear sem rumo","Cozinhar juntos"]},
{id:79,cat:1,text:"Como é que sabemos que o outro está chateado/a?",type:"choice",options:["Fica em silêncio","Fala mais do que o normal","Muda de expressão","Afasta-se um pouco"]},
{id:80,cat:1,text:"O que mais admiras na outra pessoa?",type:"choice",options:["A bondade","A inteligência","O sentido de humor","A determinação"]},
{id:81,cat:1,text:"Qual é a linguagem de amor predominante na nossa relação?",type:"choice",options:["Palavras de afirmação","Toque físico","Atos de serviço","Tempo de qualidade"]},
{id:82,cat:1,text:"O que nos fez aproximar no início?",type:"choice",options:["O sentido de humor","Interesses em comum","Atração física","Conversas profundas"]},
{id:83,cat:1,text:"Como resolvemos normalmente os nossos desentendimentos?",type:"choice",options:["Conversando com calma","Dando espaço primeiro","Com humor","Comprometendo-nos ambos"]},
{id:84,cat:1,text:"Qual a coisa mais importante para manter a nossa relação forte?",type:"choice",options:["Confiança","Comunicação","Respeito","Diversão"]},
{id:85,cat:1,text:"Que casal de ficção nos representa melhor?",type:"choice",options:["Jim e Pam (The Office)","Monica e Chandler (Friends)","Carl e Ellie (Up)","Gomez e Morticia (Addams Family)"]},
{id:86,cat:1,text:"Quando sentes mais ligação comigo?",type:"choice",options:["Quando rimos juntos","Quando conversamos a sério","Quando estamos em silêncio confortável","Quando fazemos algo novo juntos"]},
{id:87,cat:1,text:"Qual é o nosso maior desafio enquanto casal?",type:"choice",options:["A distância/tempo juntos","Diferenças de personalidade","Gerir o stress","Planear o futuro"]},
{id:88,cat:1,text:"De 1 a 10, quão bem comunicas os teus sentimentos na relação?",type:"scale",options:[]},
{id:89,cat:1,text:"De 1 a 10, quão bem conheces os sonhos e medos do/a teu/tua parceiro/a?",type:"scale",options:[]},
{id:90,cat:1,text:"De 1 a 10, quão satisfeito/a estás com o tempo de qualidade que passamos juntos?",type:"scale",options:[]},
{id:91,cat:1,text:"De 1 a 10, quão forte é a nossa cumplicidade?",type:"scale",options:[]},
{id:92,cat:1,text:"De 1 a 10, quão à vontade te sentes para seres tu mesmo/a comigo?",type:"scale",options:[]},
{id:93,cat:1,text:"De 1 a 10, quão bons somos a resolver conflitos?",type:"scale",options:[]},
{id:94,cat:1,text:"De 1 a 10, quanto sentes que te apoio nos teus objetivos?",type:"scale",options:[]},
{id:95,cat:1,text:"De 1 a 10, quanto rimos juntos no dia a dia?",type:"scale",options:[]},
{id:96,cat:1,text:"Qual foi o momento em que soubeste que me amavas?",type:"text",options:[]},
{id:97,cat:1,text:"O que é que eu faço que te irrita, mas que no fundo achas graça?",type:"text",options:[]},
{id:98,cat:1,text:"Qual é a nossa piada interna favorita?",type:"text",options:[]},
{id:99,cat:1,text:"O que mudou em ti desde que estamos juntos?",type:"text",options:[]},
{id:100,cat:1,text:"Escreve algo que nunca me disseste mas que sempre quiseste dizer.",type:"text",options:[]},
// ===== CAT 2: Sonhos & Futuro (101-150) =====
{id:101,cat:2,text:"Preferias viajar pelo mundo inteiro ou ter a casa perfeita?",type:"thisorthat",options:["Viajar pelo mundo","Casa perfeita"]},
{id:102,cat:2,text:"Preferias ser rico/a e famoso/a ou ter uma vida simples e tranquila?",type:"thisorthat",options:["Rico/a e famoso/a","Vida simples e tranquila"]},
{id:103,cat:2,text:"Preferias ter mais tempo livre ou mais dinheiro?",type:"thisorthat",options:["Mais tempo livre","Mais dinheiro"]},
{id:104,cat:2,text:"Preferias casar numa praia tropical ou num castelo em Portugal?",type:"thisorthat",options:["Praia tropical","Castelo em Portugal"]},
{id:105,cat:2,text:"Preferias abrir um negócio juntos ou seguir carreiras separadas?",type:"thisorthat",options:["Negócio juntos","Carreiras separadas"]},
{id:106,cat:2,text:"Preferias viver perto da família ou num país diferente e exótico?",type:"thisorthat",options:["Perto da família","País diferente"]},
{id:107,cat:2,text:"Preferias reformar-te cedo e viver com menos ou trabalhar mais e ter mais conforto?",type:"thisorthat",options:["Reformar cedo","Mais conforto"]},
{id:108,cat:2,text:"Preferias ter um casamento grande e festivo ou uma cerimónia íntima?",type:"thisorthat",options:["Casamento grande","Cerimónia íntima"]},
{id:109,cat:2,text:"Preferias viver no campo com animais ou na cidade com tudo à mão?",type:"thisorthat",options:["Campo com animais","Cidade com tudo à mão"]},
{id:110,cat:2,text:"Preferias aprender uma língua nova juntos ou um desporto novo juntos?",type:"thisorthat",options:["Língua nova","Desporto novo"]},
{id:111,cat:2,text:"Preferias ter uma carrinha equipada para viajar ou uma casa de férias fixa?",type:"thisorthat",options:["Carrinha equipada","Casa de férias fixa"]},
{id:112,cat:2,text:"Preferias que os nossos filhos fossem bilingues ou que aprendessem um instrumento musical?",type:"thisorthat",options:["Bilingues","Instrumento musical"]},
{id:113,cat:2,text:"Preferias ter sucesso profissional enorme ou uma vida familiar perfeita?",type:"thisorthat",options:["Sucesso profissional","Vida familiar perfeita"]},
{id:114,cat:2,text:"Preferias envelhecer numa casa cheia de netos ou a viajar o mundo?",type:"thisorthat",options:["Casa cheia de netos","Viajar o mundo"]},
{id:115,cat:2,text:"Preferias construir a nossa própria casa ou renovar uma casa antiga?",type:"thisorthat",options:["Construir de raiz","Renovar uma antiga"]},
{id:116,cat:2,text:"Preferias ter um jardim enorme ou uma piscina em casa?",type:"thisorthat",options:["Jardim enorme","Piscina"]},
{id:117,cat:2,text:"Preferias passar um ano sabático a viajar ou a estudar algo novo?",type:"thisorthat",options:["Viajar","Estudar algo novo"]},
{id:118,cat:2,text:"Preferias que escrevessem um livro sobre a nossa história de amor ou que fizessem um filme?",type:"thisorthat",options:["Livro","Filme"]},
{id:119,cat:2,text:"Preferias viver à beira-mar ou à beira de um lago nas montanhas?",type:"thisorthat",options:["Beira-mar","Lago nas montanhas"]},
{id:120,cat:2,text:"Preferias investir em experiências ou em bens materiais?",type:"thisorthat",options:["Experiências","Bens materiais"]},
{id:121,cat:2,text:"Preferias ter um emprego que adoras com salário médio ou um emprego razoável com salário excelente?",type:"thisorthat",options:["Emprego que adoro, salário médio","Emprego razoável, salário excelente"]},
{id:122,cat:2,text:"Preferias comemorar cada aniversário de namoro num sítio novo ou ter o 'nosso' restaurante especial?",type:"thisorthat",options:["Sítio novo sempre","O nosso restaurante especial"]},
{id:123,cat:2,text:"Preferias adotar um animal de um abrigo ou comprar de uma raça específica?",type:"thisorthat",options:["Adotar de um abrigo","Raça específica"]},
{id:124,cat:2,text:"Preferias ganhar o Euromilhões ou ter a garantia de saúde perfeita para sempre?",type:"thisorthat",options:["Ganhar o Euromilhões","Saúde perfeita para sempre"]},
{id:125,cat:2,text:"Preferias voltar ao passado para reviver um momento ou ir ao futuro para ver como estamos daqui a 20 anos?",type:"thisorthat",options:["Voltar ao passado","Ir ao futuro"]},
{id:126,cat:2,text:"Onde sonhas ir em lua de mel?",type:"choice",options:["Maldivas","Japão","Itália","Tailândia"]},
{id:127,cat:2,text:"Quantos filhos imaginas ter?",type:"choice",options:["Nenhum","Um","Dois","Três ou mais"]},
{id:128,cat:2,text:"Que tipo de casa sonhas ter?",type:"choice",options:["Moradia moderna","Quinta no campo","Apartamento de luxo na cidade","Casa rústica junto ao mar"]},
{id:129,cat:2,text:"Qual o próximo grande passo que gostarias de dar na nossa relação?",type:"choice",options:["Viver juntos","Viajar juntos por muito tempo","Noivado","Ter um animal de estimação juntos"]},
{id:130,cat:2,text:"Que tradição de casal gostarias de criar?",type:"choice",options:["Viagem anual juntos","Noite de encontro semanal","Cozinhar juntos ao domingo","Cartas escritas em datas especiais"]},
{id:131,cat:2,text:"Com que idade te imaginas a casar?",type:"choice",options:["Antes dos 25","Entre 25 e 30","Entre 30 e 35","Quando sentir que é a altura certa"]},
{id:132,cat:2,text:"Que continente gostavas de explorar juntos?",type:"choice",options:["Ásia","América do Sul","África","Oceânia"]},
{id:133,cat:2,text:"Que projeto criativo gostarias de fazer em conjunto?",type:"choice",options:["Escrever algo juntos","Fazer um vídeo/documentário","Criar um negócio","Renovar/decorar uma casa"]},
{id:134,cat:2,text:"Como imaginas os nossos natais daqui a 10 anos?",type:"choice",options:["Com filhos à volta da árvore","A viajar para um destino diferente","Com a família toda reunida","Só nós os dois, tranquilos"]},
{id:135,cat:2,text:"O que gostavas de aprender a fazer juntos?",type:"choice",options:["Dançar (salsa, bachata...)","Cozinha de um país diferente","Um desporto aquático","Uma arte ou artesanato"]},
{id:136,cat:2,text:"Que tipo de cerimónia de casamento preferias?",type:"choice",options:["Religiosa tradicional","Civil ao ar livre","Simbólica na natureza","Fuga romântica (elopement)"]},
{id:137,cat:2,text:"Onde gostavas de estar daqui a 5 anos?",type:"choice",options:["Na mesma cidade, estabilizados","A viver noutro país","Com a nossa empresa própria","Focados na família"]},
{id:138,cat:2,text:"De 1 a 10, quão otimista és em relação ao nosso futuro juntos?",type:"scale",options:[]},
{id:139,cat:2,text:"De 1 a 10, quão importante é para ti a estabilidade financeira antes de dar grandes passos?",type:"scale",options:[]},
{id:140,cat:2,text:"De 1 a 10, quanto desejas ter filhos no futuro?",type:"scale",options:[]},
{id:141,cat:2,text:"De 1 a 10, quão aberto/a estás a mudar de país por amor?",type:"scale",options:[]},
{id:142,cat:2,text:"De 1 a 10, quão importante é para ti que partilhemos os mesmos objetivos de vida?",type:"scale",options:[]},
{id:143,cat:2,text:"De 1 a 10, quão preparado/a te sentes para o próximo grande passo na nossa relação?",type:"scale",options:[]},
{id:144,cat:2,text:"De 1 a 10, quão importante é para ti o casamento?",type:"scale",options:[]},
{id:145,cat:2,text:"De 1 a 10, quanto valorizas a aventura e o risco no planeamento do futuro?",type:"scale",options:[]},
{id:146,cat:2,text:"Descreve como imaginas a nossa vida daqui a 10 anos.",type:"text",options:[]},
{id:147,cat:2,text:"Qual é o sonho que ainda não me contaste?",type:"text",options:[]},
{id:148,cat:2,text:"Que nome darias ao nosso futuro filho ou filha?",type:"text",options:[]},
{id:149,cat:2,text:"Qual é o lugar no mundo que mais queres visitar comigo e porquê?",type:"text",options:[]},
{id:150,cat:2,text:"O que gostarias que as pessoas dissessem sobre a nossa relação?",type:"text",options:[]},
// ===== CAT 3: Recordações (151-200) =====
{id:151,cat:3,text:"O que recordas mais do nosso primeiro encontro: o que eu vesti ou o que eu disse?",type:"thisorthat",options:["O que vestiste","O que disseste"]},
{id:152,cat:3,text:"A nossa primeira viagem juntos foi mais divertida ou mais romântica?",type:"thisorthat",options:["Mais divertida","Mais romântica"]},
{id:153,cat:3,text:"Preferias reviver o nosso primeiro beijo ou o nosso primeiro 'eu amo-te'?",type:"thisorthat",options:["Primeiro beijo","Primeiro 'eu amo-te'"]},
{id:154,cat:3,text:"Qual recordação de infância te é mais querida: uma com a família ou uma com amigos?",type:"thisorthat",options:["Com a família","Com amigos"]},
{id:155,cat:3,text:"Tinhas mais vergonha ou mais confiança no nosso primeiro encontro?",type:"thisorthat",options:["Mais vergonha","Mais confiança"]},
{id:156,cat:3,text:"O nosso momento mais engraçado juntos envolveu comida ou uma situação embaraçosa?",type:"thisorthat",options:["Comida","Situação embaraçosa"]},
{id:157,cat:3,text:"Qual aniversário de namoro foi melhor: o primeiro ou o mais recente?",type:"thisorthat",options:["O primeiro","O mais recente"]},
{id:158,cat:3,text:"Quando eras criança, eras mais traquina ou mais sossegado/a?",type:"thisorthat",options:["Mais traquina","Mais sossegado/a"]},
{id:159,cat:3,text:"O que te marcou mais na escola: os professores ou os colegas?",type:"thisorthat",options:["Os professores","Os colegas"]},
{id:160,cat:3,text:"A tua melhor memória de verão é de praia ou de aldeia/campo?",type:"thisorthat",options:["Praia","Aldeia/Campo"]},
{id:161,cat:3,text:"O presente mais especial que te dei foi algo material ou algo simbólico?",type:"thisorthat",options:["Material","Simbólico"]},
{id:162,cat:3,text:"O que te marcou mais no início da nossa relação: a atração ou a ligação emocional?",type:"thisorthat",options:["Atração","Ligação emocional"]},
{id:163,cat:3,text:"Preferias ter um vídeo do nosso primeiro encontro ou uma fotografia desse momento?",type:"thisorthat",options:["Vídeo","Fotografia"]},
{id:164,cat:3,text:"Na adolescência, eras mais tímido/a ou mais extrovertido/a?",type:"thisorthat",options:["Mais tímido/a","Mais extrovertido/a"]},
{id:165,cat:3,text:"Qual foi mais emocionante: o dia em que nos conhecemos ou o dia em que começámos a namorar?",type:"thisorthat",options:["Dia em que nos conhecemos","Dia em que começámos a namorar"]},
{id:166,cat:3,text:"A tua memória favorita de Natal é da infância ou de adulto?",type:"thisorthat",options:["Da infância","De adulto"]},
{id:167,cat:3,text:"Recordas melhor os cheiros ou os sons da tua infância?",type:"thisorthat",options:["Os cheiros","Os sons"]},
{id:168,cat:3,text:"O nosso momento mais difícil juntos tornou-nos mais fortes ou mais sábios?",type:"thisorthat",options:["Mais fortes","Mais sábios"]},
{id:169,cat:3,text:"A nossa primeira discussão foi séria ou por uma coisa parva?",type:"thisorthat",options:["Séria","Coisa parva"]},
{id:170,cat:3,text:"Quando pedes um desejo, pensas no passado ou no futuro?",type:"thisorthat",options:["No passado","No futuro"]},
{id:171,cat:3,text:"A pessoa que mais te influenciou na vida foi um familiar ou alguém de fora da família?",type:"thisorthat",options:["Familiar","Alguém de fora da família"]},
{id:172,cat:3,text:"Eras o/a favorito/a dos avós ou o/a traquina que levava ralhetes?",type:"thisorthat",options:["Favorito/a dos avós","Traquina que levava ralhetes"]},
{id:173,cat:3,text:"A nossa viagem mais memorável foi a mais planeada ou a mais improvisada?",type:"thisorthat",options:["Mais planeada","Mais improvisada"]},
{id:174,cat:3,text:"Achas que nos apaixonámos à primeira vista ou foi algo que cresceu com o tempo?",type:"thisorthat",options:["À primeira vista","Cresceu com o tempo"]},
{id:175,cat:3,text:"A melhor surpresa que te fiz foi planeada por mim sozinho/a ou com ajuda?",type:"thisorthat",options:["Sozinho/a","Com ajuda"]},
{id:176,cat:3,text:"Qual foi o melhor presente que já recebeste na vida?",type:"choice",options:["Algo feito à mão","Uma viagem","Um objeto especial","Uma experiência inesquecível"]},
{id:177,cat:3,text:"Qual era o teu sonho de criança em termos de profissão?",type:"choice",options:["Médico/a","Astronauta","Professor/a","Artista/Músico/a"]},
{id:178,cat:3,text:"Qual é a tua memória favorita da escola?",type:"choice",options:["Os intervalos com amigos","Uma viagem de estudo","Um professor especial","Uma conquista académica"]},
{id:179,cat:3,text:"Qual foi o melhor momento do nosso último aniversário?",type:"choice",options:["O jantar","A surpresa/presente","As palavras trocadas","Simplesmente estar juntos"]},
{id:180,cat:3,text:"Qual é a tua recordação de infância mais feliz?",type:"choice",options:["Férias em família","Brincadeiras com amigos","Uma festa de aniversário","Um momento especial com os pais/avós"]},
{id:181,cat:3,text:"O que mais te marcou no nosso primeiro encontro?",type:"choice",options:["O nervosismo","A conversa fácil","Um momento engraçado","A química instantânea"]},
{id:182,cat:3,text:"Qual foi o momento mais embaraçoso da nossa relação?",type:"choice",options:["Frente aos meus pais","Frente aos teus pais","Em público com desconhecidos","Só entre nós"]},
{id:183,cat:3,text:"Qual a viagem que fizemos juntos de que guardas melhores memórias?",type:"choice",options:["A primeira","A mais recente","Uma de aventura","Uma mais relaxante"]},
{id:184,cat:3,text:"Quando eras pequeno/a, qual era a tua atividade preferida?",type:"choice",options:["Brincar ao ar livre","Ler ou desenhar","Jogar videojogos","Fazer desporto"]},
{id:185,cat:3,text:"Qual foi a melhor surpresa que alguma vez te fizeram?",type:"choice",options:["Festa surpresa de aniversário","Um presente inesperado","Uma visita inesperada de alguém","Uma viagem surpresa"]},
{id:186,cat:3,text:"O que mais te emocionou na nossa relação até hoje?",type:"choice",options:["Uma declaração de amor","Um gesto de cuidado em momento difícil","Uma surpresa elaborada","A forma como ultrapassámos um obstáculo"]},
{id:187,cat:3,text:"Qual foi o verão mais marcante da tua vida?",type:"choice",options:["Um de infância","O verão em que nos conhecemos","Uma viagem especial","Um verão de mudança pessoal"]},
{id:188,cat:3,text:"De 1 a 10, quão bem te lembras dos primeiros dias da nossa relação?",type:"scale",options:[]},
{id:189,cat:3,text:"De 1 a 10, quão feliz foi a tua infância?",type:"scale",options:[]},
{id:190,cat:3,text:"De 1 a 10, quão nostálgico/a ficas quando vês fotografias nossas antigas?",type:"scale",options:[]},
{id:191,cat:3,text:"De 1 a 10, quão boa é a tua memória para datas importantes?",type:"scale",options:[]},
{id:192,cat:3,text:"De 1 a 10, quanto te emocionas ao recordar o nosso primeiro encontro?",type:"scale",options:[]},
{id:193,cat:3,text:"De 1 a 10, quão presente estavam os teus avós na tua infância?",type:"scale",options:[]},
{id:194,cat:3,text:"De 1 a 10, quão marcante foi o teu percurso escolar para quem és hoje?",type:"scale",options:[]},
{id:195,cat:3,text:"De 1 a 10, quão saudades tens de algum momento específico que vivemos juntos?",type:"scale",options:[]},
{id:196,cat:3,text:"Qual é a tua memória favorita de todos os tempos connosco?",type:"text",options:[]},
{id:197,cat:3,text:"Qual foi o momento mais difícil que ultrapassámos juntos e o que aprendeste?",type:"text",options:[]},
{id:198,cat:3,text:"Descreve a primeira coisa que pensaste quando me viste pela primeira vez.",type:"text",options:[]},
{id:199,cat:3,text:"Qual é a recordação de infância que mais moldou quem és hoje?",type:"text",options:[]},
{id:200,cat:3,text:"Se pudesses reviver um único dia da nossa relação, qual seria e porquê?",type:"text",options:[]},
// ===== CAT 4: Comida & Bebida (201-250) =====
{id:201,cat:4,text:"Preferes comida doce ou salgada?",type:"thisorthat",options:["Doce","Salgada"]},
{id:202,cat:4,text:"Preferes café ou chá?",type:"thisorthat",options:["Café","Chá"]},
{id:203,cat:4,text:"Preferes cozinhar ou que cozinhem para ti?",type:"thisorthat",options:["Cozinhar","Que cozinhem para mim"]},
{id:204,cat:4,text:"Preferes comida caseira ou comida de restaurante?",type:"thisorthat",options:["Comida caseira","Comida de restaurante"]},
{id:205,cat:4,text:"Preferes pizza ou hambúrguer?",type:"thisorthat",options:["Pizza","Hambúrguer"]},
{id:206,cat:4,text:"Preferes vinho tinto ou vinho branco?",type:"thisorthat",options:["Vinho tinto","Vinho branco"]},
{id:207,cat:4,text:"Preferes pequeno-almoço reforçado ou jantar elaborado?",type:"thisorthat",options:["Pequeno-almoço reforçado","Jantar elaborado"]},
{id:208,cat:4,text:"Preferes comida picante ou suave?",type:"thisorthat",options:["Picante","Suave"]},
{id:209,cat:4,text:"Preferes gelado de chocolate ou gelado de fruta?",type:"thisorthat",options:["Chocolate","Fruta"]},
{id:210,cat:4,text:"Preferes pastel de nata ou bolo de chocolate?",type:"thisorthat",options:["Pastel de nata","Bolo de chocolate"]},
{id:211,cat:4,text:"Preferes sushi ou comida italiana?",type:"thisorthat",options:["Sushi","Comida italiana"]},
{id:212,cat:4,text:"Preferes comer à mesa ou no sofá a ver televisão?",type:"thisorthat",options:["À mesa","No sofá"]},
{id:213,cat:4,text:"Preferes um brunch demorado ou um lanche da tarde?",type:"thisorthat",options:["Brunch demorado","Lanche da tarde"]},
{id:214,cat:4,text:"Preferes água com gás ou sem gás?",type:"thisorthat",options:["Com gás","Sem gás"]},
{id:215,cat:4,text:"Preferes fruta fresca ou sumo natural?",type:"thisorthat",options:["Fruta fresca","Sumo natural"]},
{id:216,cat:4,text:"Preferes bacalhau ou sardinha?",type:"thisorthat",options:["Bacalhau","Sardinha"]},
{id:217,cat:4,text:"Preferes cozinha portuguesa ou cozinha asiática?",type:"thisorthat",options:["Cozinha portuguesa","Cozinha asiática"]},
{id:218,cat:4,text:"Preferes cerveja artesanal ou um cocktail elaborado?",type:"thisorthat",options:["Cerveja artesanal","Cocktail elaborado"]},
{id:219,cat:4,text:"Preferes comer fora com reserva ou descobrir um sítio novo por acaso?",type:"thisorthat",options:["Com reserva","Descobrir por acaso"]},
{id:220,cat:4,text:"Preferes pão quentinho da padaria ou tostas estaladiças?",type:"thisorthat",options:["Pão quentinho","Tostas estaladiças"]},
{id:221,cat:4,text:"Preferes comer muitas entradas pequenas ou um prato principal grande?",type:"thisorthat",options:["Muitas entradas pequenas","Prato principal grande"]},
{id:222,cat:4,text:"Preferes comer a sobremesa primeiro ou no fim?",type:"thisorthat",options:["Primeiro","No fim"]},
{id:223,cat:4,text:"Preferes um almoço de domingo em família ou um brunch a dois?",type:"thisorthat",options:["Almoço de domingo em família","Brunch a dois"]},
{id:224,cat:4,text:"Preferes comida de conforto (comfort food) ou comida saudável?",type:"thisorthat",options:["Comfort food","Comida saudável"]},
{id:225,cat:4,text:"Preferes um bom queijo ou uma boa sobremesa?",type:"thisorthat",options:["Bom queijo","Boa sobremesa"]},
{id:226,cat:4,text:"Qual é a tua cozinha internacional favorita?",type:"choice",options:["Italiana","Japonesa","Mexicana","Indiana"]},
{id:227,cat:4,text:"Qual é o teu prato português preferido?",type:"choice",options:["Francesinha","Bacalhau à Brás","Cozido à portuguesa","Arroz de marisco"]},
{id:228,cat:4,text:"Que bebida escolherias para um brinde especial?",type:"choice",options:["Champanhe","Vinho do Porto","Espumante","Cocktail especial"]},
{id:229,cat:4,text:"Qual é o teu snack favorito para uma noite de cinema?",type:"choice",options:["Pipocas","Nachos","Gomas/doces","Frutos secos"]},
{id:230,cat:4,text:"Que tipo de restaurante preferes para um encontro romântico?",type:"choice",options:["Italiano acolhedor","Japonês sofisticado","Tasca portuguesa","Fine dining"]},
{id:231,cat:4,text:"Qual a tua fruta preferida?",type:"choice",options:["Morango","Manga","Pêssego","Uva"]},
{id:232,cat:4,text:"Que sabor de gelado preferes?",type:"choice",options:["Chocolate","Baunilha","Morango","Pistácio"]},
{id:233,cat:4,text:"Como tomas o teu café?",type:"choice",options:["Curto e sem açúcar","Com leite","Meia de leite","Não bebo café"]},
{id:234,cat:4,text:"Qual é o teu doce conventual favorito?",type:"choice",options:["Pastel de nata","Travesseiro de Sintra","Ovos moles","Queijada"]},
{id:235,cat:4,text:"O que preferias para o pequeno-almoço de Dia dos Namorados?",type:"choice",options:["Panquecas com fruta","Croissants e sumo de laranja","Ovos beneditinos","Torradas com abacate"]},
{id:236,cat:4,text:"Qual a tua forma preferida de comer ovos?",type:"choice",options:["Estrelados","Mexidos","Cozidos","Em omeleta"]},
{id:237,cat:4,text:"Se abríssemos um restaurante juntos, que tipo seria?",type:"choice",options:["Brunch e cafetaria","Comida portuguesa moderna","Sushi e fusion","Pizzaria artesanal"]},
{id:238,cat:4,text:"De 1 a 10, quanto gostas de cozinhar?",type:"scale",options:[]},
{id:239,cat:4,text:"De 1 a 10, quão aventureiro/a és a experimentar comidas novas?",type:"scale",options:[]},
{id:240,cat:4,text:"De 1 a 10, quanto é que a comida influencia o teu humor?",type:"scale",options:[]},
{id:241,cat:4,text:"De 1 a 10, quão importante é para ti uma boa refeição num encontro?",type:"scale",options:[]},
{id:242,cat:4,text:"De 1 a 10, quão bom/boa cozinheiro/a te consideras?",type:"scale",options:[]},
{id:243,cat:4,text:"De 1 a 10, quanto aprecias a comida tradicional da tua região?",type:"scale",options:[]},
{id:244,cat:4,text:"De 1 a 10, quão difícil é para ti escolher num menu de restaurante?",type:"scale",options:[]},
{id:245,cat:4,text:"De 1 a 10, quanto gostas de sobremesas?",type:"scale",options:[]},
{id:246,cat:4,text:"Qual é o prato que a tua avó faz (ou fazia) melhor do que ninguém?",type:"text",options:[]},
{id:247,cat:4,text:"Se pudesses comer apenas uma refeição para o resto da vida, qual seria?",type:"text",options:[]},
{id:248,cat:4,text:"Qual é a tua memória mais especial ligada a comida?",type:"text",options:[]},
{id:249,cat:4,text:"Qual é o prato que mais gostarias de aprender a cozinhar para mim?",type:"text",options:[]},
{id:250,cat:4,text:"Descreve o jantar perfeito de Dia dos Namorados.",type:"text",options:[]},
// ===== CAT 5: Entretenimento (251-300) =====
{id:251,cat:5,text:"Noite de cinema em casa ou no cinema?",type:"thisorthat",options:["Cinema em casa","Cinema no cinema"]},
{id:252,cat:5,text:"Séries de comédia ou séries de drama?",type:"thisorthat",options:["Comédia","Drama"]},
{id:253,cat:5,text:"Ouvir música ao vivo num bar ou num grande festival?",type:"thisorthat",options:["Bar intimista","Grande festival"]},
{id:254,cat:5,text:"Filmes de animação ou filmes de ação?",type:"thisorthat",options:["Animação","Ação"]},
{id:255,cat:5,text:"Ler o livro antes ou ver o filme primeiro?",type:"thisorthat",options:["Ler o livro antes","Ver o filme primeiro"]},
{id:256,cat:5,text:"Jogos de tabuleiro ou jogos de vídeo?",type:"thisorthat",options:["Jogos de tabuleiro","Jogos de vídeo"]},
{id:257,cat:5,text:"Maratonar uma série inteira ou ver um episódio por dia?",type:"thisorthat",options:["Maratonar tudo","Um episódio por dia"]},
{id:258,cat:5,text:"Concerto de música clássica ou concerto de rock?",type:"thisorthat",options:["Música clássica","Rock"]},
{id:259,cat:5,text:"Documentários ou reality shows?",type:"thisorthat",options:["Documentários","Reality shows"]},
{id:260,cat:5,text:"Filmes românticos ou filmes de terror?",type:"thisorthat",options:["Românticos","Terror"]},
{id:261,cat:5,text:"Podcasts ou audiolivros?",type:"thisorthat",options:["Podcasts","Audiolivros"]},
{id:262,cat:5,text:"Teatro ou stand-up comedy?",type:"thisorthat",options:["Teatro","Stand-up comedy"]},
{id:263,cat:5,text:"Música portuguesa ou música internacional?",type:"thisorthat",options:["Portuguesa","Internacional"]},
{id:264,cat:5,text:"Jogos cooperativos ou jogos competitivos?",type:"thisorthat",options:["Cooperativos","Competitivos"]},
{id:265,cat:5,text:"Filmes antigos/clássicos ou filmes recentes?",type:"thisorthat",options:["Clássicos","Recentes"]},
{id:266,cat:5,text:"Karaoke ou dançar numa discoteca?",type:"thisorthat",options:["Karaoke","Discoteca"]},
{id:267,cat:5,text:"Séries com uma temporada ou séries com muitas temporadas?",type:"thisorthat",options:["Uma temporada","Muitas temporadas"]},
{id:268,cat:5,text:"Ir a um museu ou ir a um parque de diversões?",type:"thisorthat",options:["Museu","Parque de diversões"]},
{id:269,cat:5,text:"Ouvir a mesma música em repeat ou descobrir músicas novas?",type:"thisorthat",options:["Mesma em repeat","Músicas novas"]},
{id:270,cat:5,text:"Filmes com legendas ou dobragem?",type:"thisorthat",options:["Legendas","Dobragem"]},
{id:271,cat:5,text:"Musical ou ópera?",type:"thisorthat",options:["Musical","Ópera"]},
{id:272,cat:5,text:"Ver desporto ao vivo ou pela televisão?",type:"thisorthat",options:["Ao vivo","Pela televisão"]},
{id:273,cat:5,text:"Thrillers psicológicos ou comédias românticas?",type:"thisorthat",options:["Thrillers psicológicos","Comédias românticas"]},
{id:274,cat:5,text:"Criar uma playlist juntos ou cada um ouvir a sua?",type:"thisorthat",options:["Playlist juntos","Cada um a sua"]},
{id:275,cat:5,text:"Escape room ou noite de cinema temática?",type:"thisorthat",options:["Escape room","Cinema temático"]},
{id:276,cat:5,text:"Qual o teu género de filme favorito para ver a dois?",type:"choice",options:["Comédia romântica","Ação/Aventura","Terror/Suspense","Drama"]},
{id:277,cat:5,text:"Que tipo de música te põe de bom humor instantaneamente?",type:"choice",options:["Pop/Dance","Rock/Indie","R&B/Soul","Hip-hop/Rap"]},
{id:278,cat:5,text:"Se pudéssemos ir a qualquer evento, qual escolherias?",type:"choice",options:["Festival de música","Estreia de cinema","Jogo desportivo","Espetáculo de teatro"]},
{id:279,cat:5,text:"Qual a melhor plataforma de streaming?",type:"choice",options:["Netflix","HBO Max","Disney+","Amazon Prime"]},
{id:280,cat:5,text:"Que tipo de jogo preferias jogar comigo?",type:"choice",options:["Jogo de cartas","Jogo de tabuleiro estratégico","Jogo de vídeo cooperativo","Jogo de trivia"]},
{id:281,cat:5,text:"Se fizéssemos uma noite temática, qual escolherias?",type:"choice",options:["Noite de Harry Potter","Noite dos anos 80","Noite italiana","Noite de super-heróis"]},
{id:282,cat:5,text:"Qual o teu guilty pleasure em termos de TV?",type:"choice",options:["Reality shows de namoro","Telenovelas","Programas de culinária","Documentários true crime"]},
{id:283,cat:5,text:"Que tipo de livros preferes?",type:"choice",options:["Romance","Ficção científica/Fantasia","Biografias","Autoajuda/Desenvolvimento pessoal"]},
{id:284,cat:5,text:"Se pudéssemos aprender uma arte juntos, qual seria?",type:"choice",options:["Dança de salão","Pintura","Música/Instrumento","Fotografia"]},
{id:285,cat:5,text:"Que época de séries/filmes preferes?",type:"choice",options:["Anos 90","Anos 2000","Anos 2010","Atualidade"]},
{id:286,cat:5,text:"Se tivéssemos um canal de YouTube juntos, qual seria o tema?",type:"choice",options:["Viagens e aventuras","Culinária a dois","Desafios e jogos","Vlogs do dia a dia"]},
{id:287,cat:5,text:"Qual o melhor programa para um domingo à tarde chuvoso?",type:"choice",options:["Maratona de séries com pipocas","Jogar jogos de tabuleiro","Cozinhar algo novo juntos","Ler lado a lado no sofá"]},
{id:288,cat:5,text:"De 1 a 10, quanto gostas de dançar?",type:"scale",options:[]},
{id:289,cat:5,text:"De 1 a 10, quanto te consideras viciado/a em séries?",type:"scale",options:[]},
{id:290,cat:5,text:"De 1 a 10, quanto gostas de ir ao cinema?",type:"scale",options:[]},
{id:291,cat:5,text:"De 1 a 10, quão importante é a música no teu dia a dia?",type:"scale",options:[]},
{id:292,cat:5,text:"De 1 a 10, quanto te consideras gamer?",type:"scale",options:[]},
{id:293,cat:5,text:"De 1 a 10, quão aberto/a estás a experimentar géneros de filmes novos?",type:"scale",options:[]},
{id:294,cat:5,text:"De 1 a 10, quanto gostas de ir a concertos e festivais?",type:"scale",options:[]},
{id:295,cat:5,text:"De 1 a 10, quanto te consideras uma pessoa criativa?",type:"scale",options:[]},
{id:296,cat:5,text:"Qual é o filme que mais vezes já viste na vida?",type:"text",options:[]},
{id:297,cat:5,text:"Qual é a música que te lembra de nós?",type:"text",options:[]},
{id:298,cat:5,text:"Qual foi a última série que te deixou completamente vidrado/a?",type:"text",options:[]},
{id:299,cat:5,text:"Se pudesses assistir a qualquer concerto da história, qual seria?",type:"text",options:[]},
{id:300,cat:5,text:"Qual é o teu momento favorito de um filme ou série que nunca esqueces?",type:"text",options:[]},
// ===== CAT 6: Cenários & Dilemas (301-350) =====
{id:301,cat:6,text:"Preferias poder voar ou ser invisível?",type:"thisorthat",options:["Voar","Ser invisível"]},
{id:302,cat:6,text:"Preferias saber tudo sobre o futuro ou poder mudar algo no passado?",type:"thisorthat",options:["Saber o futuro","Mudar o passado"]},
{id:303,cat:6,text:"Preferias viver sem telemóvel durante um mês ou sem televisão durante um ano?",type:"thisorthat",options:["Sem telemóvel 1 mês","Sem TV 1 ano"]},
{id:304,cat:6,text:"Se ganhasses o Euromilhões, preferias investir ou gastar em experiências?",type:"thisorthat",options:["Investir","Gastar em experiências"]},
{id:305,cat:6,text:"Preferias ter a capacidade de ler mentes ou de teletransporte?",type:"thisorthat",options:["Ler mentes","Teletransporte"]},
{id:306,cat:6,text:"Preferias viver 200 anos com saúde ou viver uma vida normal mas com memória perfeita?",type:"thisorthat",options:["Viver 200 anos","Memória perfeita"]},
{id:307,cat:6,text:"Preferias que os nossos filhos herdassem a tua personalidade ou a minha?",type:"thisorthat",options:["A minha","A tua"]},
{id:308,cat:6,text:"Preferias reviver o nosso primeiro encontro ou poder planear o encontro perfeito?",type:"thisorthat",options:["Reviver o primeiro","Planear o perfeito"]},
{id:309,cat:6,text:"Preferias viver numa casa na árvore ou numa casa subaquática?",type:"thisorthat",options:["Casa na árvore","Casa subaquática"]},
{id:310,cat:6,text:"Preferias poder falar todas as línguas ou tocar todos os instrumentos?",type:"thisorthat",options:["Falar todas as línguas","Tocar todos os instrumentos"]},
{id:311,cat:6,text:"Preferias ser famoso/a e não ter privacidade ou ser desconhecido/a para sempre?",type:"thisorthat",options:["Famoso/a","Desconhecido/a"]},
{id:312,cat:6,text:"Preferias viver sem café para sempre ou sem chocolate?",type:"thisorthat",options:["Sem café","Sem chocolate"]},
{id:313,cat:6,text:"Preferias saber a data exata da tua morte ou não saber nada?",type:"thisorthat",options:["Saber a data","Não saber nada"]},
{id:314,cat:6,text:"Preferias ter um chef pessoal ou uma pessoa que limpasse a casa todos os dias?",type:"thisorthat",options:["Chef pessoal","Pessoa de limpeza"]},
{id:315,cat:6,text:"Preferias perder todas as fotos que já tiraste ou nunca mais poder tirar fotos novas?",type:"thisorthat",options:["Perder as antigas","Nunca mais tirar novas"]},
{id:316,cat:6,text:"Se só pudéssemos ter um animal de estimação para sempre, preferias cão ou gato?",type:"thisorthat",options:["Cão","Gato"]},
{id:317,cat:6,text:"Preferias ter sempre sorte no amor ou sempre sorte no dinheiro?",type:"thisorthat",options:["Sorte no amor","Sorte no dinheiro"]},
{id:318,cat:6,text:"Preferias viver num mundo sem mentiras ou num mundo sem segredos?",type:"thisorthat",options:["Sem mentiras","Sem segredos"]},
{id:319,cat:6,text:"Preferias poder parar o tempo ou poder viajar no tempo?",type:"thisorthat",options:["Parar o tempo","Viajar no tempo"]},
{id:320,cat:6,text:"Preferias ter uma memória fotográfica ou uma criatividade ilimitada?",type:"thisorthat",options:["Memória fotográfica","Criatividade ilimitada"]},
{id:321,cat:6,text:"Preferias viver sem música ou sem filmes para sempre?",type:"thisorthat",options:["Sem música","Sem filmes"]},
{id:322,cat:6,text:"Preferias ter sempre a resposta certa ou fazer sempre a pergunta certa?",type:"thisorthat",options:["Resposta certa","Pergunta certa"]},
{id:323,cat:6,text:"Preferias acordar amanhã 10 anos mais novo/a ou 10 anos mais velho/a mas mais sábio/a?",type:"thisorthat",options:["10 anos mais novo/a","10 anos mais velho/a e sábio/a"]},
{id:324,cat:6,text:"Se encontrasses uma mala com 100 mil euros na rua, devolvias ou ficavas com o dinheiro?",type:"thisorthat",options:["Devolvia","Ficava com ele"]},
{id:325,cat:6,text:"Preferias poder controlar os teus sonhos ou nunca mais precisar de dormir?",type:"thisorthat",options:["Controlar sonhos","Nunca dormir"]},
{id:326,cat:6,text:"Se pudéssemos viver numa época diferente, qual escolherias?",type:"choice",options:["Renascimento","Anos 20 (Jazz Age)","Anos 60/70","O futuro (2100)"]},
{id:327,cat:6,text:"Se ficássemos presos numa ilha deserta, o que levarias?",type:"choice",options:["Kit de sobrevivência","Biblioteca infinita","Instrumento musical","Equipamento de pesca"]},
{id:328,cat:6,text:"Se pudesses ter um superpoder por um dia, qual escolherias?",type:"choice",options:["Voar","Super-força","Invisibilidade","Controlar o tempo"]},
{id:329,cat:6,text:"Se tivéssemos de mudar de país amanhã, para onde iríamos?",type:"choice",options:["Itália","Canadá","Japão","Nova Zelândia"]},
{id:330,cat:6,text:"Se pudesses jantar com qualquer pessoa da história, quem escolherias?",type:"choice",options:["Leonardo da Vinci","Cleópatra","Albert Einstein","Frida Kahlo"]},
{id:331,cat:6,text:"Se nos transformássemos em animais, o que preferias ser?",type:"choice",options:["Águia","Golfinho","Lobo","Gato doméstico"]},
{id:332,cat:6,text:"Se pudéssemos recomeçar a vida com todo o conhecimento atual, o que farias primeiro?",type:"choice",options:["Investir em Bitcoin cedo","Estudar algo diferente","Procurar-te mais cedo","Viajar pelo mundo"]},
{id:333,cat:6,text:"Num apocalipse zombie, qual seria o teu papel no grupo?",type:"choice",options:["Líder estratega","Médico/a","Explorador/a de recursos","Cozinheiro/a e moral da equipa"]},
{id:334,cat:6,text:"Se pudesses viver num universo fictício, qual escolherias?",type:"choice",options:["Harry Potter","Star Wars","Senhor dos Anéis","Marvel"]},
{id:335,cat:6,text:"Se recebêssemos 1 milhão de euros com a condição de gastar tudo em 24 horas, o que compravas primeiro?",type:"choice",options:["Uma casa","Viagens para o ano inteiro","Um negócio próprio","Presentes para a família"]},
{id:336,cat:6,text:"Se pudesses dominar uma habilidade instantaneamente, qual seria?",type:"choice",options:["Cozinhar como um chef","Falar 10 línguas","Tocar piano","Programação avançada"]},
{id:337,cat:6,text:"Se tivéssemos de abrir um negócio juntos, o que seria?",type:"choice",options:["Restaurante/Café","Agência de viagens","Loja online","Estúdio criativo"]},
{id:338,cat:6,text:"De 1 a 10, quão preparado/a estás para um apocalipse zombie?",type:"scale",options:[]},
{id:339,cat:6,text:"De 1 a 10, quão confortável estás com a ideia de mudar de país por amor?",type:"scale",options:[]},
{id:340,cat:6,text:"De 1 a 10, quão disposto/a estarias a deixar tudo para trás e recomeçar noutro lugar?",type:"scale",options:[]},
{id:341,cat:6,text:"De 1 a 10, quanto acreditas no destino e que as coisas acontecem por uma razão?",type:"scale",options:[]},
{id:342,cat:6,text:"De 1 a 10, quão corajoso/a és quando enfrentas o desconhecido?",type:"scale",options:[]},
{id:343,cat:6,text:"De 1 a 10, quão disposto/a estarias a viver sem redes sociais para sempre?",type:"scale",options:[]},
{id:344,cat:6,text:"De 1 a 10, quão confortável ficarias se eu lesse todos os teus pensamentos?",type:"scale",options:[]},
{id:345,cat:6,text:"De 1 a 10, quão bem achas que trabalharíamos juntos profissionalmente?",type:"scale",options:[]},
{id:346,cat:6,text:"Se pudesses enviar uma mensagem ao teu eu de há 10 anos, o que dirias?",type:"text",options:[]},
{id:347,cat:6,text:"Se pudéssemos trocar de vida com outro casal famoso por um dia, qual escolherias e porquê?",type:"text",options:[]},
{id:348,cat:6,text:"Se tivesses de escrever um livro sobre a nossa história, qual seria o título?",type:"text",options:[]},
{id:349,cat:6,text:"Descreve o teu dia perfeito se o dinheiro e o tempo não fossem problema.",type:"text",options:[]},
{id:350,cat:6,text:"Se pudesses criar uma lei nova para o mundo, qual seria?",type:"text",options:[]},
// ===== CAT 7: Amor & Romance (351-400) =====
{id:351,cat:7,text:"Preferias receber uma carta de amor escrita à mão ou uma surpresa inesperada?",type:"thisorthat",options:["Carta escrita à mão","Surpresa inesperada"]},
{id:352,cat:7,text:"Jantar romântico em casa ou num restaurante sofisticado?",type:"thisorthat",options:["Jantar em casa","Restaurante sofisticado"]},
{id:353,cat:7,text:"Preferias um beijo na testa ou um beijo na mão?",type:"thisorthat",options:["Beijo na testa","Beijo na mão"]},
{id:354,cat:7,text:"Declaração de amor pública ou privada?",type:"thisorthat",options:["Pública","Privada"]},
{id:355,cat:7,text:"Preferias um fim de semana romântico na montanha ou na praia?",type:"thisorthat",options:["Montanha","Praia"]},
{id:356,cat:7,text:"Preferias receber flores sem razão ou um presente pensado no aniversário?",type:"thisorthat",options:["Flores sem razão","Presente pensado"]},
{id:357,cat:7,text:"Dormir de conchinha ou cada um no seu lado da cama?",type:"thisorthat",options:["De conchinha","Cada um no seu lado"]},
{id:358,cat:7,text:"Preferias que eu te surpreendesse com um jantar ou com um plano de fim de semana?",type:"thisorthat",options:["Surpresa de jantar","Plano de fim de semana"]},
{id:359,cat:7,text:"Dizer 'amo-te' muitas vezes ao dia ou demonstrá-lo com gestos?",type:"thisorthat",options:["Dizer muitas vezes","Demonstrar com gestos"]},
{id:360,cat:7,text:"Preferias que eu te dedicasse uma música ou que te escrevesse um poema?",type:"thisorthat",options:["Dedicar uma música","Escrever um poema"]},
{id:361,cat:7,text:"Casamento grande e festivo ou cerimónia íntima e simples?",type:"thisorthat",options:["Grande e festivo","Íntimo e simples"]},
{id:362,cat:7,text:"Preferias dar uma prenda cara ou uma prenda feita por ti?",type:"thisorthat",options:["Prenda cara","Prenda feita à mão"]},
{id:363,cat:7,text:"Primeiro encontro num café ou num passeio ao ar livre?",type:"thisorthat",options:["Café","Passeio ao ar livre"]},
{id:364,cat:7,text:"Preferias que eu fosse mais expressivo/a com palavras ou com toques?",type:"thisorthat",options:["Palavras","Toques"]},
{id:365,cat:7,text:"Noite de São Valentim clássica ou anti-Valentim (fazer algo diferente)?",type:"thisorthat",options:["Clássica","Anti-Valentim diferente"]},
{id:366,cat:7,text:"Preferias ter uma foto nossa como fundo de ecrã ou uma frase especial?",type:"thisorthat",options:["Foto nossa","Frase especial"]},
{id:367,cat:7,text:"Acordar cedo para ver o nascer do sol juntos ou ficar acordados até ver o amanhecer?",type:"thisorthat",options:["Acordar cedo","Ficar acordados a noite toda"]},
{id:368,cat:7,text:"Preferias receber um elogio sobre a tua aparência ou sobre a tua personalidade?",type:"thisorthat",options:["Aparência","Personalidade"]},
{id:369,cat:7,text:"Pedir em casamento de forma elaborada ou de forma espontânea e simples?",type:"thisorthat",options:["Elaborada","Espontânea e simples"]},
{id:370,cat:7,text:"Preferias que o nosso aniversário fosse celebrado com uma viagem ou com um presente especial?",type:"thisorthat",options:["Viagem","Presente especial"]},
{id:371,cat:7,text:"Preferias que eu te fizesse o pequeno-almoço na cama ou que te preparasse um banho relaxante?",type:"thisorthat",options:["Pequeno-almoço na cama","Banho relaxante"]},
{id:372,cat:7,text:"Ter uma música 'nossa' ou ter um sítio 'nosso'?",type:"thisorthat",options:["Uma música nossa","Um sítio nosso"]},
{id:373,cat:7,text:"Preferias que eu te mandasse uma mensagem fofa durante o dia ou que te ligasse só para dizer olá?",type:"thisorthat",options:["Mensagem fofa","Telefonema surpresa"]},
{id:374,cat:7,text:"Preferias uma massagem nos pés ou uma massagem nos ombros?",type:"thisorthat",options:["Massagem nos pés","Massagem nos ombros"]},
{id:375,cat:7,text:"Álbum de fotos físico dos nossos momentos ou álbum digital organizado?",type:"thisorthat",options:["Álbum físico","Álbum digital"]},
{id:376,cat:7,text:"Qual é a tua linguagem do amor principal?",type:"choice",options:["Palavras de afirmação","Toque físico","Atos de serviço","Tempo de qualidade"]},
{id:377,cat:7,text:"O que mais te atraiu em mim no início?",type:"choice",options:["O sorriso","O sentido de humor","A inteligência","A confiança"]},
{id:378,cat:7,text:"Qual a melhor forma de pedir desculpa?",type:"choice",options:["Dizer 'desculpa' olhos nos olhos","Escrever uma carta","Fazer algo especial para compensar","Dar espaço e depois conversar"]},
{id:379,cat:7,text:"Como preferes resolver um desentendimento?",type:"choice",options:["Conversar logo na hora","Dar tempo para pensar e falar depois","Escrever os sentimentos","Abraço primeiro, conversa depois"]},
{id:380,cat:7,text:"Qual o gesto romântico mais significativo para ti?",type:"choice",options:["Cozinhar o meu prato favorito","Lembrar-se de um detalhe importante","Planear uma surpresa","Uma mensagem longa e sincera"]},
{id:381,cat:7,text:"Qual a parte mais importante numa relação para ti?",type:"choice",options:["Confiança","Comunicação","Respeito","Diversão juntos"]},
{id:382,cat:7,text:"Como sabes que estás apaixonado/a?",type:"choice",options:["Penso nessa pessoa constantemente","Sinto borboletas no estômago","Quero partilhar tudo com ela","Faço coisas que normalmente não faria"]},
{id:383,cat:7,text:"O que mais valorizas no nosso tempo juntos?",type:"choice",options:["Conversas profundas","Rir até doer a barriga","Momentos de silêncio confortável","Aventuras e experiências novas"]},
{id:384,cat:7,text:"Qual a melhor forma de demonstrar amor no dia a dia?",type:"choice",options:["Pequenos gestos de carinho","Ajudar sem que peçam","Dizer 'amo-te' frequentemente","Dar atenção total quando estamos juntos"]},
{id:385,cat:7,text:"O que faz um relacionamento durar?",type:"choice",options:["Crescer juntos","Nunca deixar de namorar","Comunicação honesta","Aceitar as diferenças"]},
{id:386,cat:7,text:"Qual foi a fase mais bonita da nossa relação até agora?",type:"choice",options:["O início/paixão","Quando nos tornámos mais próximos","Quando superámos algo difícil juntos","Agora, neste momento"]},
{id:387,cat:7,text:"Que tipo de surpresa romântica preferes?",type:"choice",options:["Algo planeado ao detalhe","Algo completamente espontâneo","Algo simples mas significativo","Algo extravagante e memorável"]},
{id:388,cat:7,text:"De 1 a 10, quão romântico/a te consideras?",type:"scale",options:[]},
{id:389,cat:7,text:"De 1 a 10, quão importante é para ti celebrar datas especiais?",type:"scale",options:[]},
{id:390,cat:7,text:"De 1 a 10, quanto precisas de contacto físico para te sentires amado/a?",type:"scale",options:[]},
{id:391,cat:7,text:"De 1 a 10, quão confortável estás a expressar os teus sentimentos?",type:"scale",options:[]},
{id:392,cat:7,text:"De 1 a 10, quão importante é o humor numa relação?",type:"scale",options:[]},
{id:393,cat:7,text:"De 1 a 10, quanto acreditas no 'amor à primeira vista'?",type:"scale",options:[]},
{id:394,cat:7,text:"De 1 a 10, quão feliz estás na nossa relação neste momento?",type:"scale",options:[]},
{id:395,cat:7,text:"De 1 a 10, quão importante é termos hobbies em comum?",type:"scale",options:[]},
{id:396,cat:7,text:"Qual é a tua memória favorita de nós dois?",type:"text",options:[]},
{id:397,cat:7,text:"O que é que eu faço que te faz sentir mais amado/a?",type:"text",options:[]},
{id:398,cat:7,text:"Se tivesses de descrever o nosso amor em três palavras, quais seriam?",type:"text",options:[]},
{id:399,cat:7,text:"Qual foi o momento em que soubeste que eu era a pessoa certa para ti?",type:"text",options:[]},
{id:400,cat:7,text:"O que é que mais admiras em mim e que eu talvez não saiba?",type:"text",options:[]},
// ===== CAT 8: Viagens & Aventuras (401-450) =====
{id:401,cat:8,text:"Férias na praia ou férias na montanha?",type:"thisorthat",options:["Praia","Montanha"]},
{id:402,cat:8,text:"Viajar de avião ou fazer uma road trip?",type:"thisorthat",options:["Avião","Road trip"]},
{id:403,cat:8,text:"Hotel de luxo ou acampar na natureza?",type:"thisorthat",options:["Hotel de luxo","Acampar"]},
{id:404,cat:8,text:"Viagem planeada ao detalhe ou viagem espontânea sem planos?",type:"thisorthat",options:["Planeada ao detalhe","Espontânea"]},
{id:405,cat:8,text:"Preferias explorar cidades ou paisagens naturais?",type:"thisorthat",options:["Cidades","Paisagens naturais"]},
{id:406,cat:8,text:"Férias de verão na Grécia ou férias de inverno na Noruega?",type:"thisorthat",options:["Verão na Grécia","Inverno na Noruega"]},
{id:407,cat:8,text:"Comida de rua local ou restaurante recomendado?",type:"thisorthat",options:["Comida de rua","Restaurante recomendado"]},
{id:408,cat:8,text:"Mergulho no oceano ou salto de paraquedas?",type:"thisorthat",options:["Mergulho no oceano","Salto de paraquedas"]},
{id:409,cat:8,text:"Viagem a dois ou viagem em grupo com amigos?",type:"thisorthat",options:["A dois","Em grupo"]},
{id:410,cat:8,text:"Preferias visitar todas as capitais da Europa ou explorar a Ásia profundamente?",type:"thisorthat",options:["Capitais da Europa","Explorar a Ásia"]},
{id:411,cat:8,text:"Safari em África ou cruzeiro pelas Caraíbas?",type:"thisorthat",options:["Safari em África","Cruzeiro nas Caraíbas"]},
{id:412,cat:8,text:"Preferias escalar uma montanha ou navegar pelo oceano?",type:"thisorthat",options:["Escalar montanha","Navegar no oceano"]},
{id:413,cat:8,text:"Visitar museus e monumentos ou provar a gastronomia local?",type:"thisorthat",options:["Museus e monumentos","Gastronomia local"]},
{id:414,cat:8,text:"Viagem de mochila às costas ou viagem com malas de luxo?",type:"thisorthat",options:["Mochila às costas","Malas de luxo"]},
{id:415,cat:8,text:"Preferias viver um ano no estrangeiro ou fazer 12 viagens curtas num ano?",type:"thisorthat",options:["1 ano no estrangeiro","12 viagens curtas"]},
{id:416,cat:8,text:"Destino turístico popular ou destino desconhecido e remoto?",type:"thisorthat",options:["Popular","Desconhecido e remoto"]},
{id:417,cat:8,text:"Preferias ver as auroras boreais ou ver as pirâmides do Egito?",type:"thisorthat",options:["Auroras boreais","Pirâmides do Egito"]},
{id:418,cat:8,text:"Hostel divertido ou Airbnb acolhedor?",type:"thisorthat",options:["Hostel","Airbnb"]},
{id:419,cat:8,text:"Férias ativas e cheias de atividades ou férias relaxantes sem fazer nada?",type:"thisorthat",options:["Ativas","Relaxantes"]},
{id:420,cat:8,text:"Visitar o Japão na primavera (cerejeiras) ou o Canadá no outono (folhas)?",type:"thisorthat",options:["Japão na primavera","Canadá no outono"]},
{id:421,cat:8,text:"Preferias uma semana em Nova Iorque ou uma semana em Paris?",type:"thisorthat",options:["Nova Iorque","Paris"]},
{id:422,cat:8,text:"Trekking no Nepal ou mergulho na Grande Barreira de Coral?",type:"thisorthat",options:["Trekking no Nepal","Mergulho na Barreira de Coral"]},
{id:423,cat:8,text:"Preferias viajar no Interrail pela Europa ou de campervan?",type:"thisorthat",options:["Interrail","Campervan"]},
{id:424,cat:8,text:"Experimentar desportos radicais ou fazer um retiro de bem-estar?",type:"thisorthat",options:["Desportos radicais","Retiro de bem-estar"]},
{id:425,cat:8,text:"Preferias visitar a Islândia ou a Patagónia?",type:"thisorthat",options:["Islândia","Patagónia"]},
{id:426,cat:8,text:"Qual o continente que mais queres explorar?",type:"choice",options:["Ásia","América do Sul","África","Oceânia"]},
{id:427,cat:8,text:"Que tipo de alojamento preferes em viagem?",type:"choice",options:["Hotel boutique","Airbnb local","Resort all-inclusive","Acampamento/Glamping"]},
{id:428,cat:8,text:"Qual a atividade que mais gostavas de fazer numa viagem a dois?",type:"choice",options:["Aula de culinária local","Tour de vinhos","Caminhada numa trilha épica","Passeio de barco ao pôr do sol"]},
{id:429,cat:8,text:"Qual a melhor estação do ano para viajar?",type:"choice",options:["Primavera","Verão","Outono","Inverno"]},
{id:430,cat:8,text:"Se pudéssemos fazer uma viagem temática, qual escolherias?",type:"choice",options:["Rota gastronómica","Rota dos castelos","Rota das praias mais bonitas","Rota das cidades mais românticas"]},
{id:431,cat:8,text:"Quanto tempo dura a tua viagem ideal?",type:"choice",options:["Um fim de semana prolongado","Uma semana","Duas a três semanas","Um mês ou mais"]},
{id:432,cat:8,text:"Qual o meio de transporte favorito para viajar?",type:"choice",options:["Avião","Comboio","Carro","Barco"]},
{id:433,cat:8,text:"Se pudéssemos morar num sítio durante 6 meses, onde seria?",type:"choice",options:["Bali, Indonésia","Barcelona, Espanha","Tóquio, Japão","Lisboa, junto ao Tejo"]},
{id:434,cat:8,text:"Que aventura radical gostavas de experimentar comigo?",type:"choice",options:["Bungee jumping","Paraquedismo","Rafting em águas bravas","Escalada numa falésia"]},
{id:435,cat:8,text:"Qual a cidade europeia que mais queres visitar comigo?",type:"choice",options:["Roma","Amesterdão","Praga","Istambul"]},
{id:436,cat:8,text:"Se tivéssemos um ano sabático, como o passaríamos?",type:"choice",options:["Volta ao mundo","Viver numa quinta no campo","Voluntariado num país diferente","Aprender algo novo em cada país"]},
{id:437,cat:8,text:"O que nunca pode faltar na mala de viagem?",type:"choice",options:["Câmara fotográfica","Um bom livro","Snacks favoritos","Playlist preparada"]},
{id:438,cat:8,text:"De 1 a 10, quão aventureiro/a te consideras?",type:"scale",options:[]},
{id:439,cat:8,text:"De 1 a 10, quanto gostas de experimentar comida nova e diferente?",type:"scale",options:[]},
{id:440,cat:8,text:"De 1 a 10, quão confortável estás a viajar sem planos definidos?",type:"scale",options:[]},
{id:441,cat:8,text:"De 1 a 10, quão importante é viajar na tua vida?",type:"scale",options:[]},
{id:442,cat:8,text:"De 1 a 10, quão disposto/a estás a viajar para destinos fora da tua zona de conforto?",type:"scale",options:[]},
{id:443,cat:8,text:"De 1 a 10, quanto gostas de tirar fotografias durante as viagens?",type:"scale",options:[]},
{id:444,cat:8,text:"De 1 a 10, quão bem lidas com voos longos?",type:"scale",options:[]},
{id:445,cat:8,text:"De 1 a 10, quão importante é para ti conhecer a cultura local quando viajas?",type:"scale",options:[]},
{id:446,cat:8,text:"Qual é o destino de sonho que sempre quiseste visitar e porquê?",type:"text",options:[]},
{id:447,cat:8,text:"Qual foi a melhor viagem que já fizeste na vida?",type:"text",options:[]},
{id:448,cat:8,text:"Descreve a tua road trip perfeita connosco dois.",type:"text",options:[]},
{id:449,cat:8,text:"Qual é a experiência de viagem mais marcante que já tiveste?",type:"text",options:[]},
{id:450,cat:8,text:"Se pudesses planear a lua de mel perfeita, como seria?",type:"text",options:[]},
// ===== CAT 9: Personalidade & Valores (451-500) =====
{id:451,cat:9,text:"Consideras-te mais introvertido/a ou extrovertido/a?",type:"thisorthat",options:["Introvertido/a","Extrovertido/a"]},
{id:452,cat:9,text:"Tomas decisões mais com a cabeça ou com o coração?",type:"thisorthat",options:["Com a cabeça","Com o coração"]},
{id:453,cat:9,text:"Preferes ter razão ou ter paz?",type:"thisorthat",options:["Ter razão","Ter paz"]},
{id:454,cat:9,text:"És mais de planear tudo ou de ser espontâneo/a?",type:"thisorthat",options:["Planear tudo","Ser espontâneo/a"]},
{id:455,cat:9,text:"Poupar para o futuro ou aproveitar o presente?",type:"thisorthat",options:["Poupar para o futuro","Aproveitar o presente"]},
{id:456,cat:9,text:"Preferes um grupo grande de amigos ou poucos amigos muito chegados?",type:"thisorthat",options:["Grupo grande","Poucos mas chegados"]},
{id:457,cat:9,text:"Resolves os problemas sozinho/a ou precisas de falar com alguém?",type:"thisorthat",options:["Sozinho/a","Falar com alguém"]},
{id:458,cat:9,text:"Preferes ser honesto/a e magoar ou mentir para proteger?",type:"thisorthat",options:["Honesto/a mesmo que magoe","Mentir para proteger"]},
{id:459,cat:9,text:"Consideras-te mais otimista ou realista?",type:"thisorthat",options:["Otimista","Realista"]},
{id:460,cat:9,text:"Preferes estabilidade ou mudança constante?",type:"thisorthat",options:["Estabilidade","Mudança constante"]},
{id:461,cat:9,text:"Perdoar facilmente ou guardar rancor?",type:"thisorthat",options:["Perdoar facilmente","Guardar rancor"]},
{id:462,cat:9,text:"Preferes liderar ou seguir?",type:"thisorthat",options:["Liderar","Seguir"]},
{id:463,cat:9,text:"Achas mais importante ser gentil ou ser justo?",type:"thisorthat",options:["Ser gentil","Ser justo"]},
{id:464,cat:9,text:"Preferes arriscar e falhar ou nunca tentar?",type:"thisorthat",options:["Arriscar e falhar","Nunca tentar"]},
{id:465,cat:9,text:"Quando estás stressado/a, preferes ficar sozinho/a ou ter companhia?",type:"thisorthat",options:["Ficar sozinho/a","Ter companhia"]},
{id:466,cat:9,text:"Preferes ser respeitado/a ou ser amado/a?",type:"thisorthat",options:["Respeitado/a","Amado/a"]},
{id:467,cat:9,text:"Segues mais a lógica ou a intuição?",type:"thisorthat",options:["Lógica","Intuição"]},
{id:468,cat:9,text:"Preferes uma vida confortável e tranquila ou uma vida intensa e cheia de desafios?",type:"thisorthat",options:["Confortável e tranquila","Intensa e desafiante"]},
{id:469,cat:9,text:"Achas que as pessoas podem mudar fundamentalmente ou não?",type:"thisorthat",options:["Podem mudar","Não mudam"]},
{id:470,cat:9,text:"Preferes dar presentes ou receber presentes?",type:"thisorthat",options:["Dar","Receber"]},
{id:471,cat:9,text:"Exprimes a raiva logo ou guardas para ti?",type:"thisorthat",options:["Exprimo logo","Guardo para mim"]},
{id:472,cat:9,text:"Preferes trabalhar em equipa ou individualmente?",type:"thisorthat",options:["Em equipa","Individualmente"]},
{id:473,cat:9,text:"Achas mais importante ser inteligente ou ser bondoso?",type:"thisorthat",options:["Inteligente","Bondoso"]},
{id:474,cat:9,text:"Preferes aprender com os teus erros ou com os erros dos outros?",type:"thisorthat",options:["Os meus erros","Os erros dos outros"]},
{id:475,cat:9,text:"Consideras-te mais paciente ou mais impaciente?",type:"thisorthat",options:["Paciente","Impaciente"]},
{id:476,cat:9,text:"Qual é o valor mais importante para ti?",type:"choice",options:["Honestidade","Lealdade","Liberdade","Família"]},
{id:477,cat:9,text:"Como reages quando alguém te critica?",type:"choice",options:["Reflito e tento melhorar","Fico magoado/a mas aceito","Defendo-me imediatamente","Ignoro e sigo em frente"]},
{id:478,cat:9,text:"O que te motiva mais na vida?",type:"choice",options:["Amor e relações","Sucesso profissional","Experiências e aventuras","Crescimento pessoal"]},
{id:479,cat:9,text:"Como descreverias o teu temperamento?",type:"choice",options:["Calmo/a e sereno/a","Apaixonado/a e intenso/a","Divertido/a e descontraído/a","Determinado/a e focado/a"]},
{id:480,cat:9,text:"Qual o teu maior medo na vida?",type:"choice",options:["Ficar sozinho/a","Não alcançar os meus sonhos","Perder alguém que amo","Arrepender-me de não ter tentado"]},
{id:481,cat:9,text:"O que mais valorizas num amigo?",type:"choice",options:["Lealdade absoluta","Sentido de humor","Honestidade brutal","Estar sempre presente"]},
{id:482,cat:9,text:"Como preferes passar o teu tempo livre?",type:"choice",options:["Em casa a relaxar","Com amigos e família","A aprender algo novo","Ao ar livre na natureza"]},
{id:483,cat:9,text:"Qual achas que é a tua melhor qualidade?",type:"choice",options:["Empatia","Determinação","Sentido de humor","Criatividade"]},
{id:484,cat:9,text:"O que consideras um sinal de maturidade?",type:"choice",options:["Admitir quando estás errado/a","Controlar as emoções","Colocar os outros primeiro","Assumir responsabilidades"]},
{id:485,cat:9,text:"Quando enfrentas um problema, qual é a tua primeira reação?",type:"choice",options:["Analisar logicamente","Pedir ajuda","Confiar no instinto","Dormir sobre o assunto"]},
{id:486,cat:9,text:"O que te faz sentir mais realizado/a?",type:"choice",options:["Ajudar os outros","Atingir um objetivo pessoal","Ser reconhecido/a pelo trabalho","Ter equilíbrio entre vida pessoal e profissional"]},
{id:487,cat:9,text:"Qual é o teu estilo de comunicação?",type:"choice",options:["Direto/a e sem rodeios","Cuidadoso/a com as palavras","Expressivo/a e emocional","Calmo/a e ponderado/a"]},
{id:488,cat:9,text:"De 1 a 10, quão importante é a independência para ti numa relação?",type:"scale",options:[]},
{id:489,cat:9,text:"De 1 a 10, quão teimoso/a te consideras?",type:"scale",options:[]},
{id:490,cat:9,text:"De 1 a 10, quanto te importas com a opinião dos outros?",type:"scale",options:[]},
{id:491,cat:9,text:"De 1 a 10, quão bem lidas com o stress?",type:"scale",options:[]},
{id:492,cat:9,text:"De 1 a 10, quão ambicioso/a te consideras?",type:"scale",options:[]},
{id:493,cat:9,text:"De 1 a 10, quanto valorizas a tradição e os costumes?",type:"scale",options:[]},
{id:494,cat:9,text:"De 1 a 10, quão empático/a te consideras?",type:"scale",options:[]},
{id:495,cat:9,text:"De 1 a 10, quão confortável estás a sair da tua zona de conforto?",type:"scale",options:[]},
{id:496,cat:9,text:"Qual é o conselho de vida mais importante que já te deram?",type:"text",options:[]},
{id:497,cat:9,text:"O que é que gostavas de mudar em ti mesmo/a?",type:"text",options:[]},
{id:498,cat:9,text:"Qual é o teu maior sonho para o futuro?",type:"text",options:[]},
{id:499,cat:9,text:"O que significa para ti ter uma vida bem vivida?",type:"text",options:[]},
{id:500,cat:9,text:"Que legado gostavas de deixar no mundo?",type:"text",options:[]}
];
